"""
Template generation for in-process server integration tests.

Generates tests that import the generated server modules directly and use
fastmcp.Client for in-process tool invocation — no running server needed.
These tests verify tool metadata, composition, error handling, and
response normalization with mocked API clients.
"""

from ...models import ApiMetadata, ModuleSpec, SecurityConfig
from ...utils import camel_to_snake, sanitize_server_name


def generate_server_integration_tests(
    modules: dict[str, ModuleSpec],
    api_metadata: ApiMetadata,
    security_config: SecurityConfig,
) -> str:
    """Generate in-process server integration tests.

    These tests import generated server modules directly and use
    fastmcp.Client to call tools without HTTP. They mock the OpenAPI
    client so no backend is needed.

    Args:
        modules: Generated server modules
        api_metadata: API metadata
        security_config: Security configuration

    Returns:
        str: Test file content
    """
    total_tools = sum(spec.tool_count for spec in modules.values())

    # Build per-module test data
    module_imports = []
    module_tool_checks = []
    module_metadata_checks = []

    for mod_name, spec in sorted(modules.items()):
        server_module = spec.filename.replace(".py", "")
        module_imports.append(
            f"from servers.{server_module} import mcp as {mod_name}_mcp, "
            f"_format_api_error, _get_api_instances"
        )

        # Tool count check for this module
        module_tool_checks.append(f'    ("{mod_name}", {mod_name}_mcp, {spec.tool_count}),')

        # Tag check — tools in this module should have the tag (snake_case lowercase)
        expected_tag = camel_to_snake(mod_name)
        module_metadata_checks.append(f'    ("{mod_name}", {mod_name}_mcp, "{expected_tag}"),')

    imports_block = "\n".join(module_imports)
    tool_check_block = "\n".join(module_tool_checks)
    metadata_check_block = "\n".join(module_metadata_checks)

    return f'''"""
Generated Server Integration Tests for {api_metadata.title}

In-process tests that import server modules directly and use fastmcp.Client
for tool invocation without needing a running HTTP server.

Tests cover:
- Server module imports and FastMCP instance creation
- Tool count per module and total
- Tool metadata (tags, timeout, parameter schemas)
- Composition via mount namespaces
- Error formatting helpers
- API client instance creation
- Tool execution with mocked OpenAPI client
- Response normalization (None, dict, list, Pydantic model, primitive)

Generated by mcp_generator — DO NOT EDIT MANUALLY
"""

import asyncio
import json
import sys
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

# Add the generated server source to the path
_project_root = Path(__file__).resolve().parent.parent.parent
_src_path = _project_root / "generated_mcp"
_generated_path = _project_root / "generated_openapi"
for _p in [str(_src_path), str(_generated_path)]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

from fastmcp import FastMCP, Client

# Import each generated server module
{imports_block}

# Import the main composition server
from {sanitize_server_name(api_metadata.title)}_mcp_generated import (
    app as main_app,
    _compose_mcp_servers,
    create_server,
    TOTAL_TOOL_COUNT,
    API_TITLE,
    API_VERSION,
)


# ---------------------------------------------------------------------------
# Module-level test data
# ---------------------------------------------------------------------------

MODULE_TOOL_COUNTS = [
{tool_check_block}
]

MODULE_TAG_EXPECTATIONS = [
{metadata_check_block}
]


# ---------------------------------------------------------------------------
# Server Import & Instance Tests
# ---------------------------------------------------------------------------


class TestServerModuleImports:
    """Verify that each generated server module imports and exposes an mcp instance."""

    @pytest.mark.parametrize("mod_name, mcp_instance, expected_count", MODULE_TOOL_COUNTS)
    def test_mcp_instance_is_fastmcp(self, mod_name, mcp_instance, expected_count):
        \"\"\"Each server module must export a FastMCP instance.\"\"\"
        assert isinstance(mcp_instance, FastMCP), (
            f"{{mod_name}}: expected FastMCP, got {{type(mcp_instance)}}"
        )

    @pytest.mark.parametrize("mod_name, mcp_instance, expected_count", MODULE_TOOL_COUNTS)
    @pytest.mark.asyncio
    async def test_tool_count_per_module(self, mod_name, mcp_instance, expected_count):
        \"\"\"Each module must register the expected number of tools.\"\"\"
        async with Client(mcp_instance) as client:
            tools = await client.list_tools()
            assert len(tools) == expected_count, (
                f"{{mod_name}}: expected {{expected_count}} tools, got {{len(tools)}}: "
                f"{{[t.name for t in tools]}}"
            )


# ---------------------------------------------------------------------------
# Tool Metadata Tests
# ---------------------------------------------------------------------------


class TestToolMetadata:
    \"\"\"Verify tool tags, timeouts, and parameter schemas.\"\"\"

    @pytest.mark.parametrize("mod_name, mcp_instance, expected_tag", MODULE_TAG_EXPECTATIONS)
    @pytest.mark.asyncio
    async def test_tools_have_module_tag(self, mod_name, mcp_instance, expected_tag):
        \"\"\"Each tool must be tagged with its module name.\"\"\"
        tools = await mcp_instance.list_tools()
        for tool_mcp in tools:
            tool_obj = await mcp_instance.get_tool(tool_mcp.name)
            if tool_obj.tags:
                assert expected_tag in tool_obj.tags, (
                    f"{{tool_mcp.name}}: expected tag '{{expected_tag}}' in {{tool_obj.tags}}"
                )

    @pytest.mark.parametrize("mod_name, mcp_instance, expected_count", MODULE_TOOL_COUNTS)
    @pytest.mark.asyncio
    async def test_tools_have_timeout(self, mod_name, mcp_instance, expected_count):
        \"\"\"Each tool should have a timeout set (default 30s).\"\"\"
        tools = await mcp_instance.list_tools()
        for tool_mcp in tools:
            tool_obj = await mcp_instance.get_tool(tool_mcp.name)
            assert tool_obj.timeout is not None, (
                f"{{tool_mcp.name}}: timeout should be set"
            )
            assert tool_obj.timeout > 0, (
                f"{{tool_mcp.name}}: timeout should be positive, got {{tool_obj.timeout}}"
            )

    @pytest.mark.parametrize("mod_name, mcp_instance, expected_count", MODULE_TOOL_COUNTS)
    @pytest.mark.asyncio
    async def test_tools_have_descriptions(self, mod_name, mcp_instance, expected_count):
        \"\"\"Each tool must have a non-empty description.\"\"\"
        async with Client(mcp_instance) as client:
            tools = await client.list_tools()
            for tool in tools:
                assert tool.description, (
                    f"{{tool.name}}: description is empty"
                )

    @pytest.mark.parametrize("mod_name, mcp_instance, expected_count", MODULE_TOOL_COUNTS)
    @pytest.mark.asyncio
    async def test_tools_have_valid_input_schemas(self, mod_name, mcp_instance, expected_count):
        \"\"\"Each tool must expose a JSON Schema for its parameters.\"\"\"
        async with Client(mcp_instance) as client:
            tools = await client.list_tools()
            for tool in tools:
                schema = tool.inputSchema
                assert isinstance(schema, dict), (
                    f"{{tool.name}}: inputSchema should be dict, got {{type(schema)}}"
                )
                assert schema.get("type") == "object", (
                    f"{{tool.name}}: inputSchema type should be 'object'"
                )


# ---------------------------------------------------------------------------
# Composition Tests
# ---------------------------------------------------------------------------


class TestComposition:
    \"\"\"Verify that mount-based composition works correctly.\"\"\"

    @pytest.mark.asyncio
    async def test_create_server_returns_fastmcp(self):
        \"\"\"create_server() factory must return a FastMCP app.\"\"\"
        server = await create_server()
        assert isinstance(server, FastMCP)

    @pytest.mark.asyncio
    async def test_total_tool_count_after_composition(self):
        \"\"\"Composed server must expose all tools from all modules.\"\"\"
        server = await create_server()
        async with Client(server) as client:
            tools = await client.list_tools()
            assert len(tools) == {total_tools}, (
                f"Expected {{TOTAL_TOOL_COUNT}} tools after composition, got {{len(tools)}}: "
                f"{{[t.name for t in tools]}}"
            )

    @pytest.mark.asyncio
    async def test_tools_are_namespaced(self):
        \"\"\"After mounting, tool names should include namespace prefix.\"\"\"
        server = await create_server()
        async with Client(server) as client:
            tools = await client.list_tools()
            tool_names = [t.name for t in tools]
            # Each tool name should contain an underscore
            # (namespace_toolname pattern from mount)
            for name in tool_names:
                assert "_" in name, (
                    f"Tool '{{name}}' doesn't appear namespaced"
                )

    def test_api_metadata_constants(self):
        \"\"\"Metadata constants should match source spec.\"\"\"
        assert API_TITLE == "{api_metadata.title}"
        assert API_VERSION == "{api_metadata.version}"
        assert TOTAL_TOOL_COUNT == {total_tools}


# ---------------------------------------------------------------------------
# Error Formatting Tests
# ---------------------------------------------------------------------------


class TestErrorFormatting:
    \"\"\"Test _format_api_error helper across all modules.\"\"\"

    @pytest.fixture
    def mock_api_exception(self):
        \"\"\"Factory for mock ApiException objects.\"\"\"
        def _make(status: int, reason: str = "error"):
            exc = MagicMock()
            exc.status = status
            exc.reason = reason
            return exc
        return _make

    @pytest.mark.parametrize("mod_name, mcp_instance, expected_count", MODULE_TOOL_COUNTS)
    def test_401_message(self, mod_name, mcp_instance, expected_count, mock_api_exception):
        \"\"\"401 should mention authentication.\"\"\"
        # Import _format_api_error from the module
        module = sys.modules[mcp_instance.__class__.__module__]
        if not hasattr(module, '_format_api_error'):
            # Get it from the server module
            server_mod = f"servers.{{mod_name}}_server"
            if server_mod in sys.modules:
                module = sys.modules[server_mod]
        msg = _format_api_error(mock_api_exception(401))
        assert "authentication" in msg.lower() or "auth" in msg.lower()

    def test_403_message(self, mock_api_exception):
        msg = _format_api_error(mock_api_exception(403))
        assert "permission" in msg.lower() or "denied" in msg.lower()

    def test_404_message(self, mock_api_exception):
        msg = _format_api_error(mock_api_exception(404))
        assert "not found" in msg.lower()

    def test_500_message(self, mock_api_exception):
        msg = _format_api_error(mock_api_exception(500))
        assert "server error" in msg.lower() or "backend" in msg.lower()

    def test_unknown_status(self, mock_api_exception):
        msg = _format_api_error(mock_api_exception(418, "I'm a teapot"))
        assert "418" in msg


# ---------------------------------------------------------------------------
# API Client Factory Tests
# ---------------------------------------------------------------------------


class TestApiClientFactory:
    \"\"\"Test _get_api_instances helper.\"\"\"

    def test_returns_dict(self):
        \"\"\"_get_api_instances must return a dict.\"\"\"
        mock_client = MagicMock()
        result = _get_api_instances(mock_client)
        assert isinstance(result, dict)
        assert len(result) > 0

    def test_values_are_api_instances(self):
        \"\"\"Each value should be an API class instance.\"\"\"
        mock_client = MagicMock()
        result = _get_api_instances(mock_client)
        for key, val in result.items():
            assert val is not None, f"API instance for '{{key}}' is None"


# ---------------------------------------------------------------------------
# Tool Execution with Mocked Backend
# ---------------------------------------------------------------------------


class TestToolExecutionMocked:
    \"\"\"Call tools via fastmcp.Client with a mocked OpenAPI client.\"\"\"

    @pytest.mark.asyncio
    async def test_tool_call_with_none_response(self):
        \"\"\"Tool should handle None API response gracefully.\"\"\"
        # Create a minimal server with a mock tool
        test_mcp = FastMCP("mock_test")

        @test_mcp.tool
        async def mock_tool() -> dict[str, Any]:
            # Simulate the response normalization code from generated tools
            response = None
            if response is None:
                result = None
            elif hasattr(response, 'to_dict') and callable(response.to_dict):
                result = response.to_dict()
            else:
                result = response
            return {{"result": result}}

        async with Client(test_mcp) as client:
            result = await client.call_tool("mock_tool", {{}})
            assert not result.is_error

    @pytest.mark.asyncio
    async def test_tool_call_with_dict_response(self):
        \"\"\"Tool should pass through dict responses.\"\"\"
        test_mcp = FastMCP("mock_test")

        @test_mcp.tool
        async def mock_tool() -> dict[str, Any]:
            response = {{"id": 1, "name": "test"}}
            if isinstance(response, (dict, str, int, float, bool)):
                result = response
            else:
                result = response
            return {{"result": result}}

        async with Client(test_mcp) as client:
            result = await client.call_tool("mock_tool", {{}})
            assert not result.is_error
            assert result.data["result"]["id"] == 1

    @pytest.mark.asyncio
    async def test_tool_call_with_list_response(self):
        \"\"\"Tool should handle list of dicts.\"\"\"
        test_mcp = FastMCP("mock_test")

        @test_mcp.tool
        async def mock_tool() -> dict[str, Any]:
            response = [{{"id": 1}}, {{"id": 2}}]
            if isinstance(response, list):
                result = []
                for item in response:
                    if hasattr(item, 'to_dict') and callable(item.to_dict):
                        result.append(item.to_dict())
                    else:
                        result.append(item)
            else:
                result = response
            return {{"result": result}}

        async with Client(test_mcp) as client:
            result = await client.call_tool("mock_tool", {{}})
            assert not result.is_error
            assert len(result.data["result"]) == 2

    @pytest.mark.asyncio
    async def test_tool_call_with_pydantic_model_response(self):
        \"\"\"Tool should call to_dict() on Pydantic-like responses.\"\"\"
        test_mcp = FastMCP("mock_test")

        @test_mcp.tool
        async def mock_tool() -> dict[str, Any]:
            # Simulate a Pydantic model with to_dict()
            response = MagicMock()
            response.to_dict.return_value = {{"id": 42, "status": "available"}}
            if hasattr(response, 'to_dict') and callable(response.to_dict):
                result = response.to_dict()
            else:
                result = response
            return {{"result": result}}

        async with Client(test_mcp) as client:
            result = await client.call_tool("mock_tool", {{}})
            assert not result.is_error
            assert result.data["result"]["id"] == 42

    @pytest.mark.asyncio
    async def test_tool_call_with_list_of_models(self):
        \"\"\"Tool should call to_dict() on each item in a list.\"\"\"
        test_mcp = FastMCP("mock_test")

        @test_mcp.tool
        async def mock_tool() -> dict[str, Any]:
            item1 = MagicMock()
            item1.to_dict.return_value = {{"id": 1}}
            item2 = MagicMock()
            item2.to_dict.return_value = {{"id": 2}}
            response = [item1, item2]
            if isinstance(response, list):
                result = []
                for item in response:
                    if hasattr(item, 'to_dict') and callable(item.to_dict):
                        result.append(item.to_dict())
                    else:
                        result.append(item)
            else:
                result = response
            return {{"result": result}}

        async with Client(test_mcp) as client:
            result = await client.call_tool("mock_tool", {{}})
            assert not result.is_error
            assert result.data["result"] == [{{"id": 1}}, {{"id": 2}}]

    @pytest.mark.asyncio
    async def test_tool_call_with_tuple_response(self):
        \"\"\"Tool should convert tuples to lists.\"\"\"
        test_mcp = FastMCP("mock_test")

        @test_mcp.tool
        async def mock_tool() -> dict[str, Any]:
            response = (1, 2, 3)
            if isinstance(response, tuple):
                result = list(response) if response else []
            else:
                result = response
            return {{"result": result}}

        async with Client(test_mcp) as client:
            result = await client.call_tool("mock_tool", {{}})
            assert not result.is_error
            assert result.data["result"] == [1, 2, 3]


# ---------------------------------------------------------------------------
# Config Loading Tests
# ---------------------------------------------------------------------------


class TestConfigLoading:
    \"\"\"Verify fastmcp.json can be loaded and parsed.\"\"\"

    def test_fastmcp_json_exists(self):
        \"\"\"fastmcp.json must exist in the server directory.\"\"\"
        config_path = _src_path / "fastmcp.json"
        assert config_path.exists(), f"fastmcp.json not found at {{config_path}}"

    def test_fastmcp_json_valid(self):
        \"\"\"fastmcp.json must be valid JSON.\"\"\"
        config_path = _src_path / "fastmcp.json"
        with open(config_path, encoding="utf-8") as f:
            config = json.load(f)
        assert isinstance(config, dict)

    def test_features_section_present(self):
        \"\"\"features section must exist in fastmcp.json.\"\"\"
        config_path = _src_path / "fastmcp.json"
        with open(config_path, encoding="utf-8") as f:
            config = json.load(f)
        assert "features" in config

    def test_composition_strategy(self):
        \"\"\"composition strategy should be 'mount'.\"\"\"
        config_path = _src_path / "fastmcp.json"
        with open(config_path, encoding="utf-8") as f:
            config = json.load(f)
        assert config.get("composition", {{}}).get("strategy") == "mount"

    def test_pyproject_toml_exists(self):
        \"\"\"pyproject.toml must exist.\"\"\"
        pyproject_path = _src_path / "pyproject.toml"
        assert pyproject_path.exists()

    def test_pyproject_requires_fastmcp_3(self):
        \"\"\"pyproject.toml must depend on fastmcp>=3.1.\"\"\"
        pyproject_path = _src_path / "pyproject.toml"
        content = pyproject_path.read_text(encoding="utf-8")
        assert "fastmcp>=" in content
        assert "fastmcp>=3" in content
'''
