"""
Template generation for authentication flow tests.

Generates pytest tests demonstrating OAuth2 authentication flows.
"""

from ...models import ApiMetadata, ModuleSpec, SecurityConfig


def generate_auth_flow_tests(
    api_metadata: ApiMetadata,
    security_config: SecurityConfig,
    modules: dict[str, ModuleSpec],
    available_flows: set[str],
) -> str:
    """
    Generate authentication flow demonstration tests.

    Args:
        api_metadata: API metadata
        security_config: Security configuration
        modules: Generated server modules
        available_flows: Set of OAuth flow names from spec

    Returns:
        Complete test file content
    """

    # Pick a sample module/tool for demonstration
    sample_module = None
    for module_spec in modules.values():
        if module_spec.tool_count > 0:
            sample_module = module_spec.api_var_name.replace("_api", "")
            break
    sample_tool = f"{sample_module}_list" if sample_module else None

    # Determine which flows to generate tests for
    has_client_credentials = "clientCredentials" in available_flows
    has_authorization_code = "authorizationCode" in available_flows
    has_password = "password" in available_flows
    has_bearer = security_config and any(
        scheme.get("type") == "http" and scheme.get("scheme") == "bearer"
        for scheme in security_config.schemes.values()
    )

    # Build documentation of available flows
    flow_docs = []
    if has_client_credentials:
        flow_docs.append("- OAuth2 Client Credentials (service-to-service)")
    if has_authorization_code:
        flow_docs.append("- OAuth2 Authorization Code (user login)")
    if has_password:
        flow_docs.append("- OAuth2 Password Grant (username/password)")
    if has_bearer:
        flow_docs.append("- HTTP Bearer Token")

    flows_description = "\n".join(flow_docs) if flow_docs else "- Check OpenAPI spec for details"
    flows_list = ", ".join(available_flows) if available_flows else "None configured"

    # Generate header
    code = f'''"""
Generated Authentication Flow Tests for {api_metadata.title}

This file demonstrates different authentication flows supported by the MCP server.
These tests serve as examples for integrating with the server.

Generated by mcp_generator from openapi.json - DO NOT EDIT MANUALLY
Regenerate using: python -m mcp_generator

Authentication Methods Supported:
{flows_description}

OAuth Flows discovered from OpenAPI spec:
{flows_list}
"""

import pytest
import httpx
import asyncio
from typing import Optional
import os


@pytest.fixture
def backend_api_url():
    """
    Backend API URL for token acquisition.

    Configured via API_BASE_URL environment variable.
    Falls back to localhost:8445 if not set.
    """
    return os.getenv("API_BASE_URL", "http://localhost:8445")


@pytest.fixture
def mcp_server_url():
    """
    MCP Server URL.

    Configured via MCP_SERVER_URL environment variable.
    Falls back to localhost:8000/mcp if not set.
    """
    return os.getenv("MCP_SERVER_URL", "http://localhost:8000/mcp")


@pytest.fixture
def oauth_client_id():
    """
    OAuth2 Client ID for testing.

    Configure via OAUTH_CLIENT_ID environment variable.
    Tests will be skipped if not set.

    Example: export OAUTH_CLIENT_ID="your-client-id"
    """
    return os.getenv("OAUTH_CLIENT_ID")


@pytest.fixture
def oauth_client_secret():
    """
    OAuth2 Client Secret for testing.

    Configure via OAUTH_CLIENT_SECRET environment variable.
    Tests will be skipped if not set.

    Example: export OAUTH_CLIENT_SECRET="your-client-secret"
    """
    return os.getenv("OAUTH_CLIENT_SECRET")


class TestAuthenticationFlows:
    """
    Demonstration tests for authentication flows.

    These tests show how to:
    1. Obtain tokens from the backend OAuth server
    2. Use tokens to authenticate with the MCP server
    3. Call MCP tools with proper authentication
    """
'''

    # Add OAuth2 Client Credentials flow test
    if has_client_credentials:
        code += '''

    @pytest.mark.asyncio
    async def test_oauth2_client_credentials_flow(
        self, backend_api_url, mcp_server_url, oauth_client_id, oauth_client_secret
    ):
        """
        Demo: OAuth2 Client Credentials Flow

        This flow is for service-to-service authentication where a client
        (like an AI agent) authenticates using client credentials.

        Prerequisites:
            Set environment variables:
            - OAUTH_CLIENT_ID: Your OAuth2 client ID
            - OAUTH_CLIENT_SECRET: Your OAuth2 client secret

        Steps:
        1. Request token from backend OAuth server using client credentials
        2. Use the access token to initialize MCP session
        3. Call MCP tools with the authenticated session
        """
        # Skip if credentials not provided
        if not oauth_client_id or not oauth_client_secret:
            pytest.skip(
                "OAuth credentials not configured. Set OAUTH_CLIENT_ID and "
                "OAUTH_CLIENT_SECRET environment variables to run this test."
            )

        async with httpx.AsyncClient() as client:
            # Step 1: Get access token using client credentials
            print("\\n📝 Step 1: Requesting access token...")
            print(f"   Using client ID: {oauth_client_id}")
            token_response = await client.post(
                f"{backend_api_url}/auth/token",
                data={
                    "grant_type": "client_credentials",
                    "client_id": oauth_client_id,
                    "client_secret": oauth_client_secret,
                    "scope": "openid profile email"
                },
                headers={"Content-Type": "application/x-www-form-urlencoded"},
                timeout=5.0
            )

            assert token_response.status_code == 200, f"Token request failed: {token_response.text}"
            token_data = token_response.json()
            access_token = token_data["access_token"]
            print(f"✅ Access token obtained: {access_token[:20]}...")

            # Step 2: Initialize MCP session with token
            print("\\n📝 Step 2: Initializing MCP session...")
            init_response = await client.post(
                mcp_server_url,
                json={
                    "jsonrpc": "2.0",
                    "id": "init-1",
                    "method": "initialize",
                    "params": {
                        "protocolVersion": "2025-03-26",
                        "capabilities": {},
                        "clientInfo": {
                            "name": "auth-demo-client",
                            "version": "1.0"
                        }
                    }
                },
                headers={
                    "Authorization": f"Bearer {access_token}",
                    "Content-Type": "application/json",
                    "Accept": "application/json, text/event-stream"
                }
            )

            assert init_response.status_code == 200, f"Initialize failed: {init_response.text}"

            # Extract session ID from response headers
            session_id = init_response.headers.get("mcp-session-id")
            print(f"✅ MCP session initialized (Session ID: {session_id})")

            # Step 3: List available tools
            print("\\n📝 Step 3: Listing available tools...")
            tools_headers = {
                "Authorization": f"Bearer {access_token}",
                "Content-Type": "application/json",
                "Accept": "application/json, text/event-stream"
            }
            if session_id:
                tools_headers["mcp-session-id"] = session_id

            tools_response = await client.post(
                mcp_server_url,
                json={
                    "jsonrpc": "2.0",
                    "id": "tools-1",
                    "method": "tools/list",
                    "params": {}
                },
                headers=tools_headers
            )

            assert tools_response.status_code == 200
            print(f"✅ Tools retrieved successfully")
'''

        # Add sample tool call if available
        if sample_tool:
            code += f'''

            # Step 4: Call a sample tool
            print("\\n📝 Step 4: Calling sample tool '{sample_tool}'...")
            try:
                tool_headers = {{
                    "Authorization": f"Bearer {{access_token}}",
                    "Content-Type": "application/json",
                    "Accept": "application/json, text/event-stream"
                }}
                if session_id:
                    tool_headers["mcp-session-id"] = session_id

                tool_response = await client.post(
                    mcp_server_url,
                    json={{
                        "jsonrpc": "2.0",
                        "id": "tool-1",
                        "method": "tools/call",
                        "params": {{
                            "name": "{sample_tool}",
                            "arguments": {{}}  # Add required arguments here
                        }}
                    }},
                    headers=tool_headers
                )

                print(f"✅ Tool call completed with status: {{tool_response.status_code}}")
                # Note: Tool may require specific arguments or return 401 if backend auth is needed
            except Exception as e:
                print(f"⚠️  Tool call example: {{e}}")
'''

    # Add JWT Bearer Token test
    if has_bearer:
        code += '''

    @pytest.mark.asyncio
    async def test_bearer_token_authentication(
        self, backend_api_url, mcp_server_url, oauth_client_id, oauth_client_secret
    ):
        """
        Demo: Bearer Token Authentication

        This demonstrates using a JWT bearer token directly.
        The token can be obtained from any OAuth2 flow.

        Prerequisites:
            Set environment variables:
            - OAUTH_CLIENT_ID: Your OAuth2 client ID
            - OAUTH_CLIENT_SECRET: Your OAuth2 client secret

        Steps:
        1. Obtain JWT token (from OAuth flow, or provided)
        2. Use token in Authorization header
        3. Make MCP requests
        """
        # Skip if credentials not provided
        if not oauth_client_id or not oauth_client_secret:
            pytest.skip(
                "OAuth credentials not configured. Set OAUTH_CLIENT_ID and "
                "OAUTH_CLIENT_SECRET environment variables to run this test."
            )

        async with httpx.AsyncClient() as client:
            # For this demo, get token via client credentials
            # In practice, this could be from any auth flow
            print("\\n📝 Obtaining JWT token...")
            token_response = await client.post(
                f"{backend_api_url}/auth/token",
                data={
                    "grant_type": "client_credentials",
                    "client_id": oauth_client_id,
                    "client_secret": oauth_client_secret,
                    "scope": "openid profile"
                },
                headers={"Content-Type": "application/x-www-form-urlencoded"}
            )

            if token_response.status_code == 200:
                jwt_token = token_response.json()["access_token"]
                print(f"✅ JWT token: {jwt_token[:50]}...")

                # Use the token
                print("\\n📝 Using JWT token to call MCP server...")
                response = await client.post(
                    mcp_server_url,
                    json={
                        "jsonrpc": "2.0",
                        "id": "ping",
                        "method": "ping"
                    },
                    headers={
                        "Authorization": f"Bearer {jwt_token}",
                        "Content-Type": "application/json"
                    }
                )

                print(f"✅ Request completed: {response.status_code}")
'''

    # Add error handling demonstration
    code += '''

    @pytest.mark.asyncio
    async def test_authentication_errors(self, mcp_server_url):
        """
        Demo: Authentication Error Handling

        This demonstrates what happens with invalid or missing authentication.
        """
        async with httpx.AsyncClient() as client:
            print("\\n📝 Testing without authentication...")

            # Attempt 1: No auth token
            response = await client.post(
                mcp_server_url,
                json={
                    "jsonrpc": "2.0",
                    "id": "test",
                    "method": "tools/list",
                    "params": {}
                },
                headers={"Content-Type": "application/json"}
            )

            print(f"No auth: Status {response.status_code}")
            print(f"Response: {response.text[:200]}")

            # Attempt 2: Invalid token
            print("\\n📝 Testing with invalid token...")
            response = await client.post(
                mcp_server_url,
                json={
                    "jsonrpc": "2.0",
                    "id": "test",
                    "method": "tools/list",
                    "params": {}
                },
                headers={
                    "Authorization": "Bearer invalid-token-here",
                    "Content-Type": "application/json"
                }
            )

            print(f"Invalid token: Status {response.status_code}")
            print(f"Response: {response.text[:200]}")
'''

    # Add token refresh flow documentation (skipped test)
    if has_authorization_code or has_password:
        code += '''

    @pytest.mark.asyncio
    async def test_token_refresh_flow(self, backend_api_url):
        """
        Demo: Token Refresh Flow

        This demonstrates how to refresh an access token using a refresh token.
        Refresh tokens are typically available with Authorization Code and Password flows.

        Note: This is a documentation-only test. Actual token refresh testing requires
        a refresh token from a previous Authorization Code or Password Grant flow.
        """
        pytest.skip(
            "Token refresh flow requires a refresh_token from Authorization Code or "
            "Password Grant flow. This is a documentation-only test showing the structure.\\n\\n"
            "To refresh a token:\\n"
            f"POST {{backend_api_url}}/auth/token\\n"
            "Content-Type: application/x-www-form-urlencoded\\n\\n"
            "grant_type=refresh_token&\\n"
            "refresh_token=<your_refresh_token>&\\n"
            "client_id=<your_client_id>&\\n"
            "client_secret=<your_client_secret>\\n\\n"
            "Response will contain new access_token and refresh_token."
        )
'''

    # Add complete workflow example
    code += f'''


class TestAuthenticationExamples:
    """
    Practical examples for different use cases.
    """

    @pytest.mark.asyncio
    async def test_complete_workflow_example(
        self, backend_api_url, mcp_server_url, oauth_client_id, oauth_client_secret
    ):
        """
        Complete Example: AI Agent Workflow

        This shows a complete workflow for an AI agent:
        1. Authenticate
        2. Discover available tools
        3. Execute tool calls
        4. Handle responses

        Prerequisites:
            Set environment variables:
            - OAUTH_CLIENT_ID: Your OAuth2 client ID
            - OAUTH_CLIENT_SECRET: Your OAuth2 client secret
        """
        # Skip if credentials not provided
        if not oauth_client_id or not oauth_client_secret:
            pytest.skip(
                "OAuth credentials not configured. Set OAUTH_CLIENT_ID and "
                "OAUTH_CLIENT_SECRET environment variables to run this test."
            )

        async with httpx.AsyncClient(timeout=10.0) as client:
            print("\\n" + "="*60)
            print("AI AGENT WORKFLOW EXAMPLE")
            print("="*60)

            # Phase 1: Authentication
            print("\\n🔐 Phase 1: Authentication")
            print("-" * 40)
            token_response = await client.post(
                f"{{backend_api_url}}/auth/token",
                data={{
                    "grant_type": "client_credentials",
                    "client_id": oauth_client_id,
                    "client_secret": oauth_client_secret,
                    "scope": "openid profile email"
                }},
                headers={{"Content-Type": "application/x-www-form-urlencoded"}}
            )

            if token_response.status_code != 200:
                pytest.skip(f"Backend not available: {{token_response.status_code}}")

            access_token = token_response.json()["access_token"]
            print(f"✅ Authenticated - Token: {{access_token[:30]}}...")

            # Phase 2: Initialize MCP
            print("\\n🚀 Phase 2: Initialize MCP Session")
            print("-" * 40)
            init_response = await client.post(
                mcp_server_url,
                json={{
                    "jsonrpc": "2.0",
                    "id": "init",
                    "method": "initialize",
                    "params": {{
                        "protocolVersion": "2025-03-26",
                        "capabilities": {{}},
                        "clientInfo": {{
                            "name": "ai-agent-demo",
                            "version": "1.0.0"
                        }}
                    }}
                }},
                headers={{
                    "Authorization": f"Bearer {{access_token}}",
                    "Content-Type": "application/json",
                    "Accept": "application/json, text/event-stream"
                }}
            )

            assert init_response.status_code == 200

            # Extract session ID from response headers
            session_id = init_response.headers.get("mcp-session-id")
            print(f"✅ MCP session initialized (Session ID: {{session_id}})")

            # Phase 3: Discover Tools
            print("\\n🔍 Phase 3: Discover Available Tools")
            print("-" * 40)

            tools_headers = {{
                "Authorization": f"Bearer {{access_token}}",
                "Content-Type": "application/json",
                "Accept": "application/json, text/event-stream"
            }}
            if session_id:
                tools_headers["mcp-session-id"] = session_id

            tools_response = await client.post(
                mcp_server_url,
                json={{
                    "jsonrpc": "2.0",
                    "id": "list-tools",
                    "method": "tools/list",
                    "params": {{}}
                }},
                headers=tools_headers
            )

            assert tools_response.status_code == 200

            # Parse response (could be SSE or JSON)
            tools_data = {{}}
            if tools_response.headers.get("content-type", "").startswith("text/event-stream"):
                # Parse SSE response
                import json
                for line in tools_response.text.split('\\n'):
                    if line.startswith('data: '):
                        tools_data = json.loads(line[6:])
                        break
            else:
                tools_data = tools_response.json()

            if "result" in tools_data and "tools" in tools_data["result"]:
                tools = tools_data["result"]["tools"]
                print(f"✅ Found {{len(tools)}} tools:")
                for i, tool in enumerate(tools[:5], 1):  # Show first 5
                    print(f"   {{i}}. {{tool.get('name', 'unknown')}}")
                if len(tools) > 5:
                    print(f"   ... and {{len(tools) - 5}} more")

            print("\\n" + "="*60)
            print("✅ WORKFLOW COMPLETE")
            print("="*60)


# Run instructions
if __name__ == "__main__":
    print("""
    Authentication Flow Tests for {api_metadata.title}
    {"=" * 60}

    These tests demonstrate how to authenticate and use the MCP server.

    Prerequisites:
    1. Backend API running on port 8445
    2. MCP Server running on port 8000
    3. OAuth2 credentials (set via environment variables):

       export OAUTH_CLIENT_ID="your-client-id"
       export OAUTH_CLIENT_SECRET="your-client-secret"

       (Or on Windows: set OAUTH_CLIENT_ID=your-client-id)

    Run tests:
        pytest test_auth_flows_generated.py -v --tb=short

    Or run specific test:
        pytest test_auth_flows_generated.py::TestAuthenticationFlows::test_oauth2_client_credentials_flow -v

    Note: Tests will be skipped if OAuth credentials are not configured.
    """)
'''

    return code
