"""
Template generation for FastMCP 3.1 transform validation tests.

Generates tests that verify BM25SearchTransform, VersionFilter, and CodeMode
are correctly wired in the generated server when enabled in fastmcp.json.
"""

from ...models import ApiMetadata, ModuleSpec, SecurityConfig


def generate_transform_tests(
    api_metadata: ApiMetadata,
    security_config: SecurityConfig,
    modules: dict[str, ModuleSpec],
) -> str:
    """Generate tests for FastMCP 3.1 transforms.

    Args:
        api_metadata: API metadata
        security_config: Security configuration
        modules: Generated server modules

    Returns:
        str: Test file content for transform validation
    """
    return f'''"""
Generated Transform Tests for {api_metadata.title}

Tests for FastMCP 3.1 server transforms:
- BM25SearchTransform (tool discovery search)
- VersionFilter (component version filtering)
- CodeMode (experimental meta-tool)
- ResponseLimitingMiddleware (response truncation)

These tests verify that transforms are correctly activated based on
the fastmcp.json feature flags.

Generated by mcp_generator - DO NOT EDIT MANUALLY
"""

import json
import os
import sys
from pathlib import Path

import pytest
import httpx


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def mcp_server_url():
    """MCP Server URL."""
    return os.getenv("MCP_SERVER_URL", "http://localhost:8000/mcp")


@pytest.fixture
def fastmcp_config():
    """Load and return fastmcp.json configuration."""
    config_path = Path(__file__).parent.parent / "fastmcp.json"
    if not config_path.exists():
        config_path = Path(__file__).parent.parent.parent / "generated_mcp" / "fastmcp.json"
    if not config_path.exists():
        pytest.skip("fastmcp.json not found")
    with open(config_path, encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture
async def mcp_session(mcp_server_url):
    """Create an initialized MCP session, returning (client, session_id)."""
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            init_response = await client.post(
                mcp_server_url,
                json={{
                    "jsonrpc": "2.0",
                    "id": "init",
                    "method": "initialize",
                    "params": {{
                        "protocolVersion": "2025-03-26",
                        "capabilities": {{}},
                        "clientInfo": {{"name": "transform-test", "version": "1.0"}}
                    }}
                }},
                headers={{
                    "Content-Type": "application/json",
                    "Accept": "application/json, text/event-stream"
                }}
            )
            session_id = init_response.headers.get("mcp-session-id")

            # Complete handshake
            headers = {{"Content-Type": "application/json", "Accept": "application/json, text/event-stream"}}
            if session_id:
                headers["mcp-session-id"] = session_id
            await client.post(
                mcp_server_url,
                json={{"jsonrpc": "2.0", "method": "notifications/initialized"}},
                headers=headers,
            )
            yield client, session_id
    except (httpx.ConnectError, httpx.TimeoutException):
        pytest.skip("MCP server not available")


# ---------------------------------------------------------------------------
# SearchTools / BM25SearchTransform
# ---------------------------------------------------------------------------


class TestBM25SearchTransform:
    """Tests for BM25SearchTransform when enabled in fastmcp.json."""

    def test_search_tools_config_present(self, fastmcp_config):
        \"\"\"fastmcp.json should contain search_tools feature config.\"\"\"
        features = fastmcp_config.get("features", {{}})
        assert "search_tools" in features, "search_tools key missing from fastmcp.json features"

    def test_search_tools_has_serializer_field(self, fastmcp_config):
        \"\"\"search_tools should have a serializer field.\"\"\"
        search = fastmcp_config["features"]["search_tools"]
        assert "serializer" in search, "serializer field missing from search_tools config"

    @pytest.mark.asyncio
    async def test_search_tool_registered_when_enabled(self, fastmcp_config, mcp_session):
        \"\"\"When search_tools.enabled=true, a search tool should appear in tools/list.\"\"\"
        if not fastmcp_config.get("features", {{}}).get("search_tools", {{}}).get("enabled", False):
            pytest.skip("search_tools not enabled in fastmcp.json")

        client, session_id = mcp_session
        headers = {{"Content-Type": "application/json", "Accept": "application/json, text/event-stream"}}
        if session_id:
            headers["mcp-session-id"] = session_id

        response = await client.post(
            os.getenv("MCP_SERVER_URL", "http://localhost:8000/mcp"),
            json={{
                "jsonrpc": "2.0",
                "id": "list-tools",
                "method": "tools/list",
                "params": {{}}
            }},
            headers=headers,
        )
        assert response.status_code == 200
        # BM25SearchTransform adds a search tool to the catalog
        data = response.json()
        if "result" in data:
            tool_names = [t["name"] for t in data["result"].get("tools", [])]
            assert any("search" in name.lower() for name in tool_names), (
                f"No search tool found in tools/list. Available: {{tool_names[:10]}}"
            )


# ---------------------------------------------------------------------------
# VersionFilter
# ---------------------------------------------------------------------------


class TestVersionFilter:
    \"\"\"Tests for VersionFilter transform configuration.\"\"\"

    def test_version_filter_config_present(self, fastmcp_config):
        \"\"\"fastmcp.json should contain version_filter feature config.\"\"\"
        features = fastmcp_config.get("features", {{}})
        assert "version_filter" in features

    def test_version_filter_defaults(self, fastmcp_config):
        \"\"\"version_filter should default to disabled with include_unversioned=true.\"\"\"
        vf = fastmcp_config["features"]["version_filter"]
        assert vf.get("enabled") is False, "version_filter should be disabled by default"
        assert vf.get("include_unversioned") is True, "include_unversioned should default to true"

    def test_version_filter_has_range_fields(self, fastmcp_config):
        \"\"\"version_filter should have version_gte and version_lt fields.\"\"\"
        vf = fastmcp_config["features"]["version_filter"]
        assert "version_gte" in vf
        assert "version_lt" in vf


# ---------------------------------------------------------------------------
# CodeMode
# ---------------------------------------------------------------------------


class TestCodeMode:
    \"\"\"Tests for CodeMode transform configuration.\"\"\"

    def test_code_mode_config_present(self, fastmcp_config):
        \"\"\"fastmcp.json should contain code_mode feature config.\"\"\"
        features = fastmcp_config.get("features", {{}})
        assert "code_mode" in features

    def test_code_mode_disabled_by_default(self, fastmcp_config):
        \"\"\"CodeMode should be disabled by default (experimental).\"\"\"
        cm = fastmcp_config["features"]["code_mode"]
        assert cm.get("enabled") is False


# ---------------------------------------------------------------------------
# ResponseLimiting
# ---------------------------------------------------------------------------


class TestResponseLimiting:
    \"\"\"Tests for ResponseLimitingMiddleware configuration.\"\"\"

    def test_response_limiting_config_present(self, fastmcp_config):
        \"\"\"fastmcp.json should contain response_limiting feature config.\"\"\"
        features = fastmcp_config.get("features", {{}})
        assert "response_limiting" in features

    def test_response_limiting_enabled_by_default(self, fastmcp_config):
        \"\"\"ResponseLimiting should be enabled by default.\"\"\"
        rl = fastmcp_config["features"]["response_limiting"]
        assert rl.get("enabled") is True

    def test_response_limiting_has_max_size(self, fastmcp_config):
        \"\"\"Should have a max_size_bytes configuration.\"\"\"
        rl = fastmcp_config["features"]["response_limiting"]
        assert "max_size_bytes" in rl
        assert isinstance(rl["max_size_bytes"], int)
        assert rl["max_size_bytes"] > 0
'''
