"""
Template for generating MCP resource template tests.

Tests RFC 6570 URI template functionality and resource access patterns.
"""

from ...models import ApiMetadata, ModuleSpec, SecurityConfig


def generate_resource_tests(
    modules: dict[str, ModuleSpec], api_metadata: ApiMetadata, security_config: SecurityConfig
) -> str:
    """
    Generate tests for MCP resource templates.

    Args:
        modules: Generated server modules
        api_metadata: API metadata
        security_config: Security configuration

    Returns:
        Test file content for resource validation
    """

    # Count total resources across all modules
    total_resources = sum(spec.resource_count for spec in modules.values())

    if total_resources == 0:
        # No resources generated - return minimal test file
        return f'''"""
Generated Resource Tests for {api_metadata.title}

No resources were generated for this API (use --enable-resources flag).

Generated by mcp_generator - DO NOT EDIT MANUALLY
"""

import pytest


def test_no_resources_generated():
    """Verify that no resources were generated (expected behavior without --enable-resources)."""
    assert True  # This is a placeholder test
'''

    # Collect resource information from modules
    resources_by_module = {}
    for module_name, module_spec in modules.items():
        if module_spec.resource_count > 0:
            resources_by_module[module_name] = module_spec.resource_count

    from ...utils import sanitize_server_name

    server_name = sanitize_server_name(api_metadata.title)

    # Build the base test code
    code = f'''"""
Generated Resource Tests for {api_metadata.title}

Validates MCP resource templates using RFC 6570 URI syntax.
Resources provide URI-based access patterns complementing tool-based RPC calls.

Generated by mcp_generator - DO NOT EDIT MANUALLY
"""

import pytest
import sys
from pathlib import Path

# Add the generated_mcp directory to the path to import the server
generated_mcp_dir = Path(__file__).parent.parent.parent / "generated_mcp"
sys.path.insert(0, str(generated_mcp_dir.absolute()))

# Import FastMCP Client for proper MCP communication
try:
    from fastmcp.client import Client
    from fastmcp.client.transports import FastMCPTransport
except ImportError:
    pytest.skip("fastmcp not installed - install with: pip install fastmcp", allow_module_level=True)

# Import the generated MCP server
try:
    from {server_name}_mcp_generated import app, _compose_mcp_servers
except ImportError as e:
    pytest.skip(f"Could not import generated MCP server: {{e}}", allow_module_level=True)


@pytest.fixture
async def mcp_client():
    """Create a FastMCP client connected directly to the MCP server."""
    # Compose the servers first (mount all subservers)
    _compose_mcp_servers()

    # Use FastMCPTransport for in-process testing (no HTTP needed)
    transport = FastMCPTransport(app)
    client = Client(transport=transport)

    # Connect the client
    await client.__aenter__()

    yield client

    # Clean up
    await client.__aexit__(None, None, None)


class TestResourceDiscovery:
    """Test resource template discovery via list_resource_templates."""

    @pytest.mark.asyncio
    async def test_resources_list_endpoint(self, mcp_client):
        """Verify list_resource_templates returns all resource templates."""
        # Use FastMCP Client API to list resource templates
        templates = await mcp_client.list_resource_templates()

        # Should have {total_resources} resource templates
        assert len(templates) == {total_resources}, (
            f"Expected {total_resources} resource templates, got {{len(templates)}}"
        )

        # Each template should have required fields
        for template in templates:
            assert hasattr(template, "uriTemplate"), "Template missing uriTemplate"
            assert hasattr(template, "name"), "Template missing name"

            # URI template should use valid scheme
            uri_template = template.uriTemplate
            assert "://" in uri_template, f"Invalid URI template: {{uri_template}}"

            print(f"✓ Found resource template: {{template.name}} - {{uri_template}}")


class TestResourceAccess:
    """Test accessing resources via read_resource."""

    @pytest.mark.asyncio
    async def test_resource_templates_accessible(self, mcp_client):
        """Verify resource templates are accessible and properly configured."""
        # Get list of available resource templates
        templates = await mcp_client.list_resource_templates()

        if not templates:
            pytest.skip("No resource templates available")

        # Find a template with path parameters
        template_with_params = None
        for template in templates:
            uri_template = template.uriTemplate
            if "{{" in uri_template and "}}" in uri_template:
                template_with_params = template
                break

        if not template_with_params:
            pytest.skip("No resource templates with path parameters found")

        print(f"\\nFound resource template: {{template_with_params.uriTemplate}}")

        # Note: Actually reading the resource would require:
        # 1. Constructing a valid URI with real parameter values
        # 2. Calling client.read_resource() with that URI
        # 3. Validating the response structure
        # This would need backend connectivity, so we verify template structure only

        assert template_with_params.uriTemplate is not None
        assert template_with_params.name is not None


class TestResourceURITemplates:
    """Test RFC 6570 URI template syntax."""

    @pytest.mark.asyncio
    async def test_uri_template_syntax(self, mcp_client):
        """Verify all resource templates use valid RFC 6570 URI syntax."""
        templates = await mcp_client.list_resource_templates()

        for template in templates:
            uri_template = template.uriTemplate

            # Check for RFC 6570 features
            has_path_params = "{{" in uri_template and "}}" in uri_template
            has_query_params = "{{?" in uri_template
            has_wildcard = "{{" in uri_template and "*" in uri_template

            # Validate scheme
            assert "://" in uri_template, f"URI template missing scheme: {{uri_template}}"

            scheme = uri_template.split("://")[0]
            # Allow alphanumeric, +, -, and _ in schemes
            assert scheme.replace("+", "").replace("-", "").replace("_", "").isalnum(), (
                f"Invalid scheme: {{scheme}}"
            )

            print(f"  ✓ {{uri_template}}")
            if has_path_params:
                print(f"    - Has path parameters")
            if has_query_params:
                print(f"    - Has query parameters (RFC 6570)")
            if has_wildcard:
                print(f"    - Has wildcard parameter")

'''

    # Add module-specific test classes
    for module_name, resource_count in sorted(resources_by_module.items()):
        code += f'''
class Test{module_name}Resources:
    """Test resources from {module_name} module."""

    @pytest.mark.asyncio
    async def test_{module_name.lower()}_resource_count(self, mcp_client):
        """Verify {module_name} has {resource_count} resource template(s)."""
        # Use FastMCP Client API
        templates = await mcp_client.list_resource_templates()

        # Note: This test verifies total count across all modules
        # Individual module filtering would require metadata in the templates
        assert len(templates) >= {resource_count}, (
            f"Expected at least {resource_count} templates, got {{len(templates)}}"
        )

'''

    # Add summary comment
    code += f"""
# ============================================================================
# Test Summary
# ============================================================================
#
# Total Resources: {total_resources}
# Modules with Resources: {len(resources_by_module)}
#
# Resource Distribution:
"""
    for module_name, count in sorted(resources_by_module.items()):
        code += f"#   - {module_name}: {count} resource(s)\n"

    code += """#
# Run these tests with:
#   pytest test_resources_generated.py -v
#
# Prerequisites:
#   1. fastmcp library installed: pip install fastmcp
#   2. Server generated with --enable-resources flag
#
# Notes:
#   - These tests use FastMCP Client library for proper MCP communication
#   - Tests import and run the server in-process (no external server needed)
#   - FastMCPTransport provides direct access to the MCP server
#
# ============================================================================
"""

    return code
