"""
Template generation for tool schema validation tests.

Generates tests that cross-reference the generated MCP tool parameter schemas
against the original OpenAPI specification to catch drift and mismatches.
"""

from ...models import ApiMetadata, ModuleSpec, SecurityConfig


def generate_tool_schema_tests(
    modules: dict[str, ModuleSpec],
    api_metadata: ApiMetadata,
    security_config: SecurityConfig,
) -> str:
    """Generate tool schema validation tests.

    These tests compare the generated tools' parameter schemas against
    the original OpenAPI spec to detect drift. They also verify that
    required vs optional parameter classification is correct.

    Args:
        modules: Generated server modules
        api_metadata: API metadata
        security_config: Security configuration

    Returns:
        str: Test file content
    """
    total_tools = sum(spec.tool_count for spec in modules.values())

    # Build module import lines
    module_imports = []
    module_entries = []
    for mod_name, spec in sorted(modules.items()):
        server_module = spec.filename.replace(".py", "")
        module_imports.append(f"from servers.{server_module} import mcp as {mod_name}_mcp")
        module_entries.append(f'    ("{mod_name}", {mod_name}_mcp, {spec.tool_count}),')

    imports_block = "\n".join(module_imports)
    entries_block = "\n".join(module_entries)

    return f'''"""
Generated Tool Schema Validation Tests for {api_metadata.title}

Cross-references MCP tool schemas against the OpenAPI specification
to detect parameter drift, missing tools, and schema mismatches.

Tests cover:
- Tool-to-operation mapping completeness
- Required vs optional parameter correctness
- Parameter schema structure validation
- Deprecated tool version annotations
- Response type consistency (always dict)
- No duplicate tool names across modules

Generated by mcp_generator — DO NOT EDIT MANUALLY
"""

import json
import sys
from pathlib import Path
from typing import Any

import pytest

# Add source paths
_project_root = Path(__file__).resolve().parent.parent.parent
_src_path = _project_root / "generated_mcp"
_generated_path = _project_root / "generated_openapi"
for _p in [str(_src_path), str(_generated_path)]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

from fastmcp import Client

{imports_block}


MODULES = [
{entries_block}
]


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def openapi_spec():
    \"\"\"Load the source OpenAPI specification.\"\"\"
    for search_dir in [
        _project_root,   # project root
        _src_path,       # generated_mcp/
        Path.cwd(),
    ]:
        for name in ["openapi.json", "openapi.yaml", "openapi.yml"]:
            spec_path = search_dir / name
            if spec_path.exists():
                with open(spec_path, encoding="utf-8") as f:
                    if name.endswith(".json"):
                        return json.load(f)
                    else:
                        try:
                            import yaml
                            return yaml.safe_load(f)
                        except ImportError:
                            pytest.skip("PyYAML not installed for YAML spec")
    pytest.skip("OpenAPI spec not found")


@pytest.fixture(scope="session")
def spec_operation_ids(openapi_spec):
    \"\"\"Extract all operation IDs from the OpenAPI spec.\"\"\"
    ops = set()
    for path, methods in openapi_spec.get("paths", {{}}).items():
        for method, operation in methods.items():
            if method in ("get", "post", "put", "patch", "delete", "head", "options"):
                op_id = operation.get("operationId")
                if op_id:
                    ops.add(op_id)
    return ops


@pytest.fixture(scope="session")
def spec_operations_by_id(openapi_spec):
    \"\"\"Map operation ID -> operation spec.\"\"\"
    ops = {{}}
    for path, methods in openapi_spec.get("paths", {{}}).items():
        for method, operation in methods.items():
            if method in ("get", "post", "put", "patch", "delete", "head", "options"):
                op_id = operation.get("operationId")
                if op_id:
                    ops[op_id] = {{
                        "path": path,
                        "method": method,
                        "operation": operation,
                    }}
    return ops


# ---------------------------------------------------------------------------
# Tool Coverage
# ---------------------------------------------------------------------------


class TestToolCoverage:
    \"\"\"Verify the generated tools cover all OpenAPI operations.\"\"\"

    @pytest.mark.asyncio
    async def test_total_tool_count(self):
        \"\"\"Total tools should match expected count.\"\"\"
        total = 0
        for _, mcp_instance, expected in MODULES:
            async with Client(mcp_instance) as client:
                tools = await client.list_tools()
                total += len(tools)
        assert total == {total_tools}, (
            f"Expected {total_tools} total tools, got {{total}}"
        )

    @pytest.mark.asyncio
    async def test_no_duplicate_tool_names_across_modules(self):
        \"\"\"Tool names must be unique across all modules.\"\"\"
        all_names = []
        for mod_name, mcp_instance, _ in MODULES:
            async with Client(mcp_instance) as client:
                tools = await client.list_tools()
                for t in tools:
                    all_names.append((mod_name, t.name))

        seen = {{}}
        duplicates = []
        for mod, name in all_names:
            if name in seen:
                duplicates.append(f"{{name}} in both {{seen[name]}} and {{mod}}")
            seen[name] = mod
        assert not duplicates, f"Duplicate tool names: {{duplicates}}"


# ---------------------------------------------------------------------------
# Parameter Schema Validation
# ---------------------------------------------------------------------------


class TestParameterSchemas:
    \"\"\"Validate tool parameter schemas are well-formed.\"\"\"

    @pytest.mark.parametrize("mod_name, mcp_instance, expected_count", MODULES)
    @pytest.mark.asyncio
    async def test_all_params_are_typed(self, mod_name, mcp_instance, expected_count):
        \"\"\"Every parameter in the schema must have a type.\"\"\"
        async with Client(mcp_instance) as client:
            tools = await client.list_tools()
            for tool in tools:
                props = tool.inputSchema.get("properties", {{}})
                for param_name, param_schema in props.items():
                    # Parameters should have a type or anyOf
                    has_type = "type" in param_schema or "anyOf" in param_schema
                    assert has_type, (
                        f"{{tool.name}}.{{param_name}}: missing type in schema"
                    )

    @pytest.mark.parametrize("mod_name, mcp_instance, expected_count", MODULES)
    @pytest.mark.asyncio
    async def test_optional_params_have_defaults(self, mod_name, mcp_instance, expected_count):
        \"\"\"Optional parameters should have default values.\"\"\"
        async with Client(mcp_instance) as client:
            tools = await client.list_tools()
            for tool in tools:
                required = tool.inputSchema.get("required", [])
                props = tool.inputSchema.get("properties", {{}})
                for param_name, param_schema in props.items():
                    if param_name not in required:
                        # Optional param — should have a default
                        has_default = "default" in param_schema
                        # anyOf with null type counts as optional
                        has_null_type = any(
                            t.get("type") == "null"
                            for t in param_schema.get("anyOf", [])
                        )
                        assert has_default or has_null_type, (
                            f"{{tool.name}}.{{param_name}}: optional but no default"
                        )

    @pytest.mark.parametrize("mod_name, mcp_instance, expected_count", MODULES)
    @pytest.mark.asyncio
    async def test_no_internal_params_exposed(self, mod_name, mcp_instance, expected_count):
        \"\"\"Internal params (starting with _) must not be in tool schemas.\"\"\"
        async with Client(mcp_instance) as client:
            tools = await client.list_tools()
            for tool in tools:
                props = tool.inputSchema.get("properties", {{}})
                internal = [p for p in props if p.startswith("_")]
                assert not internal, (
                    f"{{tool.name}}: internal params exposed: {{internal}}"
                )


# ---------------------------------------------------------------------------
# Deprecated Tool Detection
# ---------------------------------------------------------------------------


class TestDeprecatedTools:
    \"\"\"Check that deprecated operations get version annotations.\"\"\"

    @pytest.mark.parametrize("mod_name, mcp_instance, expected_count", MODULES)
    @pytest.mark.asyncio
    async def test_deprecated_tools_have_version(self, mod_name, mcp_instance, expected_count):
        \"\"\"Tools marked deprecated should have version='deprecated'.\"\"\"
        tools = await mcp_instance.list_tools()
        for tool_mcp in tools:
            tool_obj = await mcp_instance.get_tool(tool_mcp.name)
            if tool_obj.version == "deprecated":
                # Good — it's marked
                assert True
            # If not deprecated, no assertion needed


# ---------------------------------------------------------------------------
# Response Structure
# ---------------------------------------------------------------------------


class TestResponseStructure:
    \"\"\"Verify tool return types and structure.\"\"\"

    @pytest.mark.parametrize("mod_name, mcp_instance, expected_count", MODULES)
    @pytest.mark.asyncio
    async def test_tools_return_dict_type(self, mod_name, mcp_instance, expected_count):
        \"\"\"Each tool function should declare dict[str, Any] return type.\"\"\"
        tools = await mcp_instance.list_tools()
        for tool_mcp in tools:
            tool_obj = await mcp_instance.get_tool(tool_mcp.name)
            fn = tool_obj.fn
            annotations = getattr(fn, "__annotations__", {{}})
            ret = annotations.get("return")
            # Return type should be dict or dict[str, Any]
            if ret is not None:
                assert "dict" in str(ret).lower() or ret is dict, (
                    f"{{tool_mcp.name}}: return type should be dict, got {{ret}}"
                )
'''
