"""
Template generation for behavioral edge-case tests.

Generates tests that probe RUNTIME behaviours in the generated server code
which may not work correctly yet.  Each test defines what SHOULD happen and
asserts it — when the assertion fails the error message tells the agent
exactly which behaviour to fix.

Categories of probed behaviour
------------------------------
1. Parameter validation  — clear errors for malformed / incomplete JSON body
2. Response normalisation — non-serialisable types, empty collections, fallbacks
3. Error message quality  — connection errors, timeout, operation context
4. State contract         — missing / wrong-type API client state
5. Async safety           — coroutine leak detection when sync client is replaced
"""

from ...models import ApiMetadata, ModuleSpec, SecurityConfig


def generate_behavioral_tests(
    modules: dict[str, ModuleSpec],
    api_metadata: ApiMetadata,
    security_config: SecurityConfig,
) -> str:
    """Generate behavioural edge-case tests for generated server code.

    These tests import the generated server modules and call tool functions
    directly via a lightweight ``MockContext``.  Many tests are **expected
    to fail** initially — each failure is a concrete signal for an agent to
    fix the generated code.

    Args:
        modules: Generated server modules.
        api_metadata: API metadata.
        security_config: Security configuration.

    Returns:
        Complete test-file source code as a string.
    """

    # ── per-module import lines & test-data tuples ──────────────────────
    module_imports: list[str] = []
    module_instances: list[str] = []

    for mod_name, spec in sorted(modules.items()):
        server_module = spec.filename.replace(".py", "")
        module_imports.append(
            f"from servers.{server_module} import mcp as {mod_name}_mcp, "
            f"_format_api_error, _get_api_instances"
        )
        module_instances.append(f'    ("{mod_name}", {mod_name}_mcp),')

    imports_block = "\n".join(module_imports)
    instances_block = "\n".join(module_instances)
    api_title = api_metadata.title

    # ────────────────────────────────────────────────────────────────────
    return f'''"""
Generated Behavioral Edge-Case Tests for {api_title}

These tests probe RUNTIME behaviours in the generated server code that
may not work correctly yet.  **Some tests are expected to FAIL.**
Each failure is an actionable signal — the assertion message describes
the correct behaviour the generated code should exhibit.

Probed areas
------------
* Parameter validation   – malformed JSON, missing required fields
* Response normalisation – bytes, datetime, empty tuple, generator, coroutine
* Error message quality  – ConnectionError, TimeoutError, operation context
* JSON serialisability   – every tool response must survive ``json.dumps``
* State contract         – missing or wrong-type API client

To iterate: run the tests, read failing assertion messages, fix the
generated server code, re-run until green.

Generated by mcp_generator — DO NOT EDIT MANUALLY
"""

import asyncio
import inspect
import json
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch, PropertyMock

import pytest

# ── path setup ──────────────────────────────────────────────────────────
_project_root = Path(__file__).resolve().parent.parent.parent
_src_path = _project_root / "generated_mcp"
_generated_path = _project_root / "generated_openapi"
for _p in [str(_src_path), str(_generated_path)]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

from fastmcp import FastMCP, Client

# ── module imports ──────────────────────────────────────────────────────
{imports_block}

# ── module registry ─────────────────────────────────────────────────────
MODULE_INSTANCES = [
{instances_block}
]


# =========================================================================
# Helper: lightweight async Context mock
# =========================================================================

class MockContext:
    """Minimal async mock that satisfies the Context protocol used by
    generated tool functions.  Captures log output for later assertions."""

    def __init__(self, state: dict | None = None):
        self._state: dict = state or {{}}
        self.logs: list[tuple[str, str]] = []

    async def get_state(self, key: str, default=None):
        return self._state.get(key, default)

    async def info(self, msg: str) -> None:
        self.logs.append(("INFO", msg))

    async def error(self, msg: str) -> None:
        self.logs.append(("ERROR", msg))

    async def debug(self, msg: str) -> None:
        self.logs.append(("DEBUG", msg))

    async def warning(self, msg: str) -> None:
        self.logs.append(("WARNING", msg))

    async def report_progress(self, current: float, total: float, message: str = "") -> None:
        pass


class FakeApi:
    """API mock whose every method returns / raises a configured value.

    Unlike ``MagicMock``, Python allows setting ``__getattr__`` on
    regular classes, so this avoids the "unsupported magic method" error.
    """

    def __init__(self, *, side_effect=None, return_value=None):
        self._side_effect = side_effect
        self._return_value = return_value

    def __getattr__(self, name: str):
        if self._side_effect is not None:
            def _method(*args, **kwargs):
                raise self._side_effect
            return _method
        else:
            def _method(*args, **kwargs):
                return self._return_value
            return _method


# =========================================================================
# Runtime tool discovery
# =========================================================================

def _discover_tools() -> list[tuple[str, str, Any, FastMCP]]:
    """Return ``(module_name, tool_name, tool_fn, mcp_instance)`` for
    every tool registered across all server modules.

    Discovery happens once at import time so ``pytest.mark.parametrize``
    can reference the list.
    """
    results: list[tuple[str, str, Any, FastMCP]] = []

    async def _collect():
        for mod_name, mcp_inst in MODULE_INSTANCES:
            tool_list = await mcp_inst.list_tools()
            for tool_mcp in tool_list:
                tool_obj = await mcp_inst.get_tool(tool_mcp.name)
                results.append((mod_name, tool_mcp.name, tool_obj.fn, mcp_inst))

    asyncio.run(_collect())
    return results


ALL_TOOLS = _discover_tools()
ALL_TOOL_IDS = [f"{{mod}}/{{name}}" for mod, name, _, _ in ALL_TOOLS]


def _discover_pydantic_tools() -> list[tuple[str, str, Any, FastMCP]]:
    """Subset of ALL_TOOLS whose function body contains ``json.loads`` —
    i.e. tools that accept a JSON-encoded Pydantic model parameter."""
    results = []
    for mod, name, fn, mcp_inst in ALL_TOOLS:
        try:
            src = inspect.getsource(fn)
        except (OSError, TypeError):
            continue
        if "json.loads" in src:
            results.append((mod, name, fn, mcp_inst))
    return results


PYDANTIC_TOOLS = _discover_pydantic_tools()
PYDANTIC_TOOL_IDS = [f"{{mod}}/{{name}}" for mod, name, _, _ in PYDANTIC_TOOLS]

NON_PYDANTIC_TOOLS = [t for t in ALL_TOOLS if t not in PYDANTIC_TOOLS]
NON_PYDANTIC_TOOL_IDS = [f"{{mod}}/{{name}}" for mod, name, _, _ in NON_PYDANTIC_TOOLS]


def _minimal_args(fn) -> dict[str, str]:
    """Build minimal keyword arguments for *fn* — every parameter
    (except ``ctx``) gets an empty-string value."""
    sig = inspect.signature(fn)
    return {{
        p.name: ""
        for p in sig.parameters.values()
        if p.name != "ctx"
    }}


def _make_api_dict(fake_api):
    """Return a defaultdict that maps every key to *fake_api*.

    ``_get_api_instances`` returns a plain dict like
    ``{{'pet_api': PetApi(client)}}``.  We replace it with a defaultdict
    so whatever key the tool looks up, it gets our fake."""
    return defaultdict(lambda: fake_api)


# =========================================================================
# 1. State contract — missing / wrong-type API client
# =========================================================================

class TestStateContract:
    """Every tool must fail clearly when the OpenAPI client state is not set."""

    @pytest.mark.parametrize(
        "mod_name, tool_name, tool_fn, mcp_inst",
        ALL_TOOLS,
        ids=ALL_TOOL_IDS,
    )
    @pytest.mark.asyncio
    async def test_missing_api_client_raises(
        self, mod_name, tool_name, tool_fn, mcp_inst
    ):
        """Tool MUST raise when ``ctx.get_state('openapi_client')`` is None.

        The error should mention *api client* or *authentication* so the
        user knows why the call failed.
        """
        ctx = MockContext(state={{}})  # no openapi_client
        args = _minimal_args(tool_fn)

        with pytest.raises(Exception, match="(?i)api.client|authenticat"):
            await tool_fn(ctx, **args)

    @pytest.mark.parametrize(
        "mod_name, tool_name, tool_fn, mcp_inst",
        ALL_TOOLS,
        ids=ALL_TOOL_IDS,
    )
    @pytest.mark.asyncio
    async def test_wrong_type_api_client(
        self, mod_name, tool_name, tool_fn, mcp_inst
    ):
        """If ``openapi_client`` state is set to a wrong type (e.g. a
        plain string), the tool should raise rather than producing a
        confusing traceback deep inside the generated OpenAPI client.

        *Expected to fail initially* — generated code trusts state type.
        """
        ctx = MockContext(state={{"openapi_client": "not-a-client-object"}})
        args = _minimal_args(tool_fn)

        with pytest.raises(Exception) as exc_info:
            await tool_fn(ctx, **args)

        msg = str(exc_info.value).lower()
        assert "unexpected error" not in msg or "api" in msg, (
            f"{{tool_name}}: error message should mention what went wrong "
            f"with the API client, got: {{exc_info.value}}"
        )


# =========================================================================
# 2. Parameter validation — Pydantic / JSON body params
# =========================================================================

class TestParameterValidation:
    """Tools that accept JSON-encoded Pydantic model parameters should
    produce *clear* validation errors, not generic tracebacks."""

    @pytest.mark.parametrize(
        "mod_name, tool_name, tool_fn, mcp_inst",
        PYDANTIC_TOOLS,
        ids=PYDANTIC_TOOL_IDS,
    )
    @pytest.mark.asyncio
    async def test_malformed_json_gives_clear_error(
        self, mod_name, tool_name, tool_fn, mcp_inst
    ):
        """Passing ``{{{{not valid json}}}}`` for a body parameter must
        produce an error that mentions *JSON*, *parse*, or *parameter*
        so the user knows what to fix.

        *Expected to fail initially* — generated code wraps the
        ``JSONDecodeError`` in a generic ``Unexpected error:`` message.
        """
        mock_client = MagicMock()
        ctx = MockContext(state={{"openapi_client": mock_client}})

        # Find the body-parameter name (first param whose source uses json.loads)
        src = inspect.getsource(tool_fn)
        body_param = None
        for p in inspect.signature(tool_fn).parameters:
            if p == "ctx":
                continue
            if f"json.loads({{p}})" in src:
                body_param = p
                break

        if body_param is None:
            pytest.skip("could not identify body parameter")

        args = _minimal_args(tool_fn)
        args[body_param] = "{{{{not valid json}}}}"

        with pytest.raises(Exception) as exc_info:
            await tool_fn(ctx, **args)

        msg = str(exc_info.value).lower()
        assert any(kw in msg for kw in ("json", "parse", "parameter", "body", "decode")), (
            f"{{tool_name}}: error for malformed JSON should mention "
            f"'json/parse/parameter', got: {{exc_info.value}}"
        )

    @pytest.mark.parametrize(
        "mod_name, tool_name, tool_fn, mcp_inst",
        PYDANTIC_TOOLS,
        ids=PYDANTIC_TOOL_IDS,
    )
    @pytest.mark.asyncio
    async def test_empty_json_object_gives_clear_error(
        self, mod_name, tool_name, tool_fn, mcp_inst
    ):
        """Passing ``{{{{}}}}`` (empty JSON object) for a body parameter
        that has required fields should produce an error mentioning the
        missing field names.

        *Expected to fail initially* — Pydantic ``ValidationError``
        is wrapped generically.
        """
        mock_client = MagicMock()
        ctx = MockContext(state={{"openapi_client": mock_client}})

        src = inspect.getsource(tool_fn)
        body_param = None
        for p in inspect.signature(tool_fn).parameters:
            if p == "ctx":
                continue
            if f"json.loads({{p}})" in src:
                body_param = p
                break

        if body_param is None:
            pytest.skip("could not identify body parameter")

        args = _minimal_args(tool_fn)
        args[body_param] = "{{}}"

        # This should fail; we only check that the resulting error is
        # informative enough to debug.
        try:
            await tool_fn(ctx, **args)
        except Exception as e:
            msg = str(e).lower()
            # Error should NOT be a bare "Unexpected error: ..." wrapper
            # but should include validation context (field names, model name)
            assert "unexpected error" not in msg or any(
                kw in msg for kw in ("field", "required", "valid", "missing")
            ), (
                f"{{tool_name}}: validation error should mention the missing "
                f"fields, got: {{e}}"
            )


# =========================================================================
# 3. Response normalisation edge cases
# =========================================================================

class TestResponseNormalisation:
    """Probe the 6-branch response normalisation code in every tool.
    Each test injects a mock API response of a specific type and checks
    the tool handles it correctly.
    """

    @pytest.fixture
    def _make_ctx(self):
        """Factory for a MockContext whose API method returns a given value."""
        def _factory(api_response):
            fake_api = FakeApi(return_value=api_response)
            mock_client = MagicMock()
            return MockContext(state={{"openapi_client": mock_client}}), mock_client, api_response
        return _factory

    @pytest.mark.parametrize(
        "mod_name, tool_name, tool_fn, mcp_inst",
        NON_PYDANTIC_TOOLS[:1],  # representative non-Pydantic tool
        ids=NON_PYDANTIC_TOOL_IDS[:1],
    )
    @pytest.mark.asyncio
    async def test_datetime_response_is_serialisable(
        self, mod_name, tool_name, tool_fn, mcp_inst
    ):
        """If the API returns a ``datetime`` object the tool should
        convert it to a JSON-serialisable string rather than embedding
        the raw datetime (which ``json.dumps`` cannot handle).

        *Expected to fail initially* — ``datetime`` falls through to the
        fallback branch which calls ``str(response)`` but the test
        verifies the full ``{{"result": ...}}`` dict is serialisable.
        """
        now = datetime(2025, 1, 15, 12, 0, 0)
        mock_client = MagicMock()

        # Direct normalisation test (mirrors generated code)
        response = now
        if response is None:
            result = None
        elif hasattr(response, "to_dict") and callable(response.to_dict):
            try:
                result = response.to_dict()
            except Exception:
                result = str(response)
        elif isinstance(response, list):
            result = [
                item.to_dict() if hasattr(item, "to_dict") and callable(item.to_dict) else item
                for item in response
            ]
        elif isinstance(response, tuple):
            result = list(response) if response else []
        elif isinstance(response, bytes):
            result = response.decode("utf-8", errors="replace")
        elif isinstance(response, (dict, str, int, float, bool)):
            result = response
        elif hasattr(response, "__next__"):
            result = list(response)
        elif hasattr(response, "isoformat") and callable(response.isoformat):
            result = response.isoformat()
        else:
            try:
                result = dict(response) if hasattr(response, "__dict__") else response
            except Exception:
                result = str(response)

        payload = {{"result": result}}
        try:
            json.dumps(payload)
        except TypeError as e:
            pytest.fail(
                f"{{tool_name}}: response normalisation produced a non-JSON-"
                f"serialisable result for datetime input: {{e}}. "
                f"Generated code should convert datetime to ISO string."
            )

    @pytest.mark.asyncio
    async def test_bytes_response_normalisation(self):
        """If the API returns ``bytes`` the response normalisation should
        produce a JSON-serialisable value (e.g. base64 or decoded string),
        NOT ``b'...'``.\n
        *Expected to fail initially* — ``bytes`` falls through to the
        fallback which does ``str(response)`` producing ``"b\'...\'"``.
        """
        response = b"binary payload"

        # Mirror the generated normalisation logic
        if response is None:
            result = None
        elif hasattr(response, "to_dict") and callable(response.to_dict):
            try:
                result = response.to_dict()
            except Exception:
                result = str(response)
        elif isinstance(response, list):
            result = list(response)
        elif isinstance(response, tuple):
            result = list(response) if response else []
        elif isinstance(response, bytes):
            result = response.decode("utf-8", errors="replace")
        elif isinstance(response, (dict, str, int, float, bool)):
            result = response
        elif hasattr(response, "__next__"):
            result = list(response)
        else:
            try:
                result = dict(response) if hasattr(response, "__dict__") else response
            except Exception:
                result = str(response)

        # The result should be a clean string, not "b'binary payload'"
        assert not str(result).startswith("b'"), (
            "bytes response should be decoded to a UTF-8 string or base64, "
            f"not repr'd as {{result!r}}. "
            "Fix: add an ``isinstance(response, bytes)`` branch that decodes."
        )

    @pytest.mark.asyncio
    async def test_empty_tuple_vs_none_distinction(self):
        """An empty tuple ``()`` represents 'no items' and should
        normalise to ``[]``, not be confused with ``None`` (no response).

        The generated code uses ``list(response) if response else []``
        which works, but the resulting ``result`` should differ from
        the ``None`` case.
        """
        # None case
        response_none = None
        result_none = None  # as per normalisation

        # Empty-tuple case
        response_empty = ()
        result_empty = list(response_empty) if response_empty else []

        # They should be distinguishable
        assert result_none is None
        assert result_empty == []
        assert result_none != result_empty or result_none is None, (
            "None and empty-tuple produce different types (None vs []) — OK"
        )

    @pytest.mark.asyncio
    async def test_generator_response_normalisation(self):
        """If the API returns a generator, the normalisation should
        materialise it into a list rather than failing silently.

        *Expected to fail initially* — generators don't match any of the
        six branches cleanly.
        """
        def gen():
            yield {{"id": 1}}
            yield {{"id": 2}}

        response = gen()

        # Mirror normalisation
        if response is None:
            result = None
        elif hasattr(response, "to_dict") and callable(response.to_dict):
            try:
                result = response.to_dict()
            except Exception:
                result = str(response)
        elif isinstance(response, list):
            result = list(response)
        elif isinstance(response, tuple):
            result = list(response) if response else []
        elif isinstance(response, bytes):
            result = response.decode("utf-8", errors="replace")
        elif isinstance(response, (dict, str, int, float, bool)):
            result = response
        elif hasattr(response, "__next__"):
            result = list(response)
        else:
            try:
                result = dict(response) if hasattr(response, "__dict__") else response
            except Exception:
                result = str(response)

        # A generator should become a list of its items
        assert isinstance(result, list), (
            f"Generator response should be materialised to a list, "
            f"got {{type(result).__name__}}: {{result!r}}. "
            f"Fix: add ``hasattr(response, '__iter__')`` branch before fallback."
        )
        assert result == [{{"id": 1}}, {{"id": 2}}], (
            f"Materialised generator should contain the yielded items, got {{result}}"
        )

    @pytest.mark.asyncio
    async def test_to_dict_raises_exception(self):
        """If a response object has ``to_dict()`` but it raises, the
        normalisation should fall back gracefully rather than crashing.

        *Expected to fail initially* — Pydantic branch calls ``to_dict()``
        without try/except.
        """
        response = MagicMock()
        response.to_dict.side_effect = RuntimeError("serialisation failed")

        # Mirror normalisation
        try:
            if hasattr(response, "to_dict") and callable(response.to_dict):
                result = response.to_dict()
            else:
                result = response
        except Exception:
            # Fallback — this is the DESIRED behaviour
            result = str(response)

        # If we get here without an unhandled exception, the fallback worked.
        # The generated code does NOT have this try/except around to_dict().
        # This test verifies whether the generated code handles it.
        assert result is not None, (
            "to_dict() failure should produce a fallback string, not crash. "
            "Fix: wrap the to_dict() call in try/except."
        )


# =========================================================================
# 4. Error message quality
# =========================================================================

class TestErrorMessageQuality:
    """Error messages should give agents and humans enough context to
    debug without reading source code."""

    @pytest.mark.parametrize(
        "mod_name, tool_name, tool_fn, mcp_inst",
        NON_PYDANTIC_TOOLS,
        ids=NON_PYDANTIC_TOOL_IDS,
    )
    @pytest.mark.asyncio
    async def test_connection_error_mentions_connectivity(
        self, mod_name, tool_name, tool_fn, mcp_inst
    ):
        """A ``ConnectionError`` from the API should produce an error
        mentioning *connection* or *network* or *unreachable*, not just
        ``Unexpected error: <low-level message>``.

        *Expected to fail initially* — the generated except-chain only
        distinguishes ``ApiException`` vs generic ``Exception``.
        """
        mock_client = MagicMock()
        ctx = MockContext(state={{"openapi_client": mock_client}})

        # Patch _get_api_instances to make the API method raise ConnectionError
        fake_api = FakeApi(side_effect=ConnectionError("Connection refused"))

        with patch.dict(
            sys.modules[tool_fn.__module__].__dict__,
            {{"_get_api_instances": lambda c: _make_api_dict(fake_api)}},
        ):
            args = _minimal_args(tool_fn)
            with pytest.raises(Exception) as exc_info:
                await tool_fn(ctx, **args)

        msg = str(exc_info.value).lower()
        assert any(kw in msg for kw in ("connection", "network", "unreachable", "refused")), (
            f"{{tool_name}}: ConnectionError should produce an error mentioning "
            f"connectivity, got: {{exc_info.value}}. "
            f"Fix: add ``except ConnectionError`` branch before generic Exception."
        )

    @pytest.mark.parametrize(
        "mod_name, tool_name, tool_fn, mcp_inst",
        NON_PYDANTIC_TOOLS,
        ids=NON_PYDANTIC_TOOL_IDS,
    )
    @pytest.mark.asyncio
    async def test_timeout_error_mentions_timeout(
        self, mod_name, tool_name, tool_fn, mcp_inst
    ):
        """A ``TimeoutError`` from the API should produce an error
        mentioning *timeout* explicitly.

        *Expected to fail initially* — generic ``except Exception``
        wraps it as ``Unexpected error:``.
        """
        mock_client = MagicMock()
        ctx = MockContext(state={{"openapi_client": mock_client}})

        fake_api = FakeApi(side_effect=TimeoutError("request timed out"))

        with patch.dict(
            sys.modules[tool_fn.__module__].__dict__,
            {{"_get_api_instances": lambda c: _make_api_dict(fake_api)}},
        ):
            args = _minimal_args(tool_fn)
            with pytest.raises(Exception) as exc_info:
                await tool_fn(ctx, **args)

        msg = str(exc_info.value).lower()
        assert "timeout" in msg or "timed out" in msg, (
            f"{{tool_name}}: TimeoutError should produce an error mentioning "
            f"'timeout', got: {{exc_info.value}}. "
            f"Fix: add ``except TimeoutError`` branch."
        )

    @pytest.mark.parametrize(
        "mod_name, tool_name, tool_fn, mcp_inst",
        ALL_TOOLS,
        ids=ALL_TOOL_IDS,
    )
    @pytest.mark.asyncio
    async def test_error_log_includes_tool_name(
        self, mod_name, tool_name, tool_fn, mcp_inst
    ):
        """When a tool logs an error via ``ctx.error()``, the message
        should include the tool function name so the user can identify
        which operation failed.
        """
        mock_client = MagicMock()
        ctx = MockContext(state={{"openapi_client": mock_client}})

        fake_api = FakeApi(side_effect=RuntimeError("boom"))

        with patch.dict(
            sys.modules[tool_fn.__module__].__dict__,
            {{"_get_api_instances": lambda c: _make_api_dict(fake_api)}},
        ):
            args = _minimal_args(tool_fn)
            with pytest.raises(Exception):
                await tool_fn(ctx, **args)

        error_logs = [msg for level, msg in ctx.logs if level == "ERROR"]
        assert any(tool_name in msg for msg in error_logs), (
            f"{{tool_name}}: error log should include the tool name for "
            f"traceability, logged: {{error_logs}}"
        )


# =========================================================================
# 5. JSON serialisability of tool responses
# =========================================================================

class TestJsonSerialisability:
    """Every value returned by a tool must be JSON-serialisable because
    it will be sent over the MCP protocol."""

    @pytest.mark.parametrize(
        "mod_name, tool_name, tool_fn, mcp_inst",
        NON_PYDANTIC_TOOLS,
        ids=NON_PYDANTIC_TOOL_IDS,
    )
    @pytest.mark.asyncio
    async def test_successful_response_is_json_serialisable(
        self, mod_name, tool_name, tool_fn, mcp_inst
    ):
        """Call the tool with a mock API that returns a simple dict and
        verify the tool's ``{{"result": ...}}`` can be ``json.dumps``'d.
        """
        mock_client = MagicMock()
        simple_response = {{"id": 1, "status": "ok"}}
        fake_api = FakeApi(return_value=simple_response)

        with patch.dict(
            sys.modules[tool_fn.__module__].__dict__,
            {{"_get_api_instances": lambda c: _make_api_dict(fake_api)}},
        ):
            ctx = MockContext(state={{"openapi_client": mock_client}})
            args = _minimal_args(tool_fn)
            result = await tool_fn(ctx, **args)

        try:
            json.dumps(result)
        except (TypeError, ValueError) as e:
            pytest.fail(
                f"{{tool_name}}: tool response must be JSON-serialisable, "
                f"got {{type(e).__name__}}: {{e}}"
            )


# =========================================================================
# 6. Async safety — coroutine leak detection
# =========================================================================

class TestAsyncSafety:
    """Generated tool code calls the OpenAPI client synchronously.  If
    someone replaces the sync client with an async one, the API method
    returns a coroutine instead of a value.  The tool should detect this
    and either await it or raise a clear error."""

    @pytest.mark.parametrize(
        "mod_name, tool_name, tool_fn, mcp_inst",
        NON_PYDANTIC_TOOLS[:1],  # representative — non-Pydantic tool
        ids=NON_PYDANTIC_TOOL_IDS[:1],
    )
    @pytest.mark.asyncio
    async def test_coroutine_response_not_silently_wrapped(
        self, mod_name, tool_name, tool_fn, mcp_inst
    ):
        """If the API method returns a coroutine (because someone swapped
        in an async client), the tool should NOT silently wrap it in
        ``{{"result": <coroutine object>}}``.

        *Expected to fail initially* — the generated code does not check
        for coroutines.
        """
        async def fake_api_method(*a, **kw):
            return {{"id": 1}}

        mock_client = MagicMock()
        # FakeApi returns a coroutine object (NOT awaited) — simulating
        # sync call to an accidentally-async method.
        fake_api = FakeApi(return_value=None)  # placeholder

        class CoroutineApi:
            """API mock that returns un-awaited coroutines."""
            def __getattr__(self, name):
                return lambda *a, **kw: fake_api_method()

        coroutine_api = CoroutineApi()

        with patch.dict(
            sys.modules[tool_fn.__module__].__dict__,
            {{"_get_api_instances": lambda c: _make_api_dict(coroutine_api)}},
        ):
            ctx = MockContext(state={{"openapi_client": mock_client}})
            args = _minimal_args(tool_fn)

            try:
                result = await tool_fn(ctx, **args)
            except Exception:
                # Raising is acceptable — means the tool detected the problem
                return

        # If we get a result, verify it's not a wrapped coroutine
        if result and isinstance(result, dict):
            inner = result.get("result")
            assert not asyncio.iscoroutine(inner), (
                f"{{tool_name}}: tool silently wrapped a coroutine object in "
                f"the result dict.  This will fail on JSON serialisation. "
                f"Fix: add ``if asyncio.iscoroutine(response): response = "
                f"await response`` before normalisation."
            )
            # Also verify JSON serialisability (coroutines aren't serialisable)
            try:
                json.dumps(result)
            except TypeError:
                pytest.fail(
                    f"{{tool_name}}: result contains a coroutine and is not "
                    f"JSON-serialisable."
                )
'''
