"""
Template generation for real tools/call E2E tests.

Generates pytest tests that actually invoke each generated MCP tool via
tools/call over HTTP and verify the response structure. This is the only
test suite that exercises the full stack: MCP protocol → generated tool →
OpenAPI client → backend API → response.

Strategy:
- GET tools are called with example/dummy args and responses are validated
- Write tools (POST/PUT/DELETE) are called to verify the tool responds
  (backend may return 4xx which is OK — we verify the MCP layer works)
- All tests require a running MCP server (set MCP_SERVER_URL env var)
"""

from typing import Any

from ...models import ApiMetadata, ModuleSpec, SecurityConfig
from ...utils import camel_to_snake, sanitize_name


def _extract_operations(openapi_spec: dict[str, Any]) -> list[dict[str, Any]]:
    """Extract operations from OpenAPI spec with tool name mapping.

    Returns a list of dicts with:
        tool_name, http_method, path, operation_id, tag, parameters, has_body, summary
    """
    operations: list[dict[str, Any]] = []

    for path, path_item in openapi_spec.get("paths", {}).items():
        if not isinstance(path_item, dict):
            continue

        for method in ("get", "post", "put", "delete", "patch"):
            operation = path_item.get(method)
            if not isinstance(operation, dict):
                continue

            operation_id = operation.get("operationId", "")
            if not operation_id:
                continue

            tags = operation.get("tags", [])
            primary_tag = tags[0] if tags else "default"

            # Build tool name: Tag_sanitized_operation_id
            snake_op = camel_to_snake(operation_id)
            sanitized = sanitize_name(snake_op)
            tool_name = f"{primary_tag.title().replace(' ', '')}_{sanitized}"

            # Extract path/query parameters
            params: list[dict[str, str]] = []
            for param in operation.get("parameters", []) + path_item.get("parameters", []):
                if isinstance(param, dict) and param.get("name"):
                    params.append(
                        {
                            "name": camel_to_snake(param["name"]),
                            "in": param.get("in", "query"),
                            "required": param.get("required", False),
                            "type": param.get("schema", {}).get("type", "string"),
                            "example": param.get("example"),
                            "enum": param.get("schema", {}).get("enum"),
                        }
                    )

            # Check for request body
            has_body = "requestBody" in operation

            operations.append(
                {
                    "tool_name": tool_name,
                    "http_method": method.upper(),
                    "path": path,
                    "operation_id": operation_id,
                    "tag": primary_tag,
                    "parameters": params,
                    "has_body": has_body,
                    "summary": operation.get("summary", operation_id),
                }
            )

    return operations


def _example_value(param: dict[str, str]) -> str:
    """Generate a safe example value for a parameter."""
    if param.get("example"):
        return repr(param["example"])
    if param.get("enum"):
        return repr(param["enum"][0])
    param_type = param.get("type", "string")
    if param_type == "integer":
        return '"1"'
    if param_type == "number":
        return '"1.0"'
    if param_type == "boolean":
        return '"true"'
    return '"test"'


def generate_tool_call_tests(
    modules: dict[str, ModuleSpec],
    api_metadata: ApiMetadata,
    security_config: SecurityConfig,
    openapi_spec: dict[str, Any],
) -> str:
    """Generate real tools/call E2E tests for every tool.

    Args:
        modules: Generated server modules
        api_metadata: API metadata
        security_config: Security configuration
        openapi_spec: Parsed OpenAPI specification

    Returns:
        Complete test file content
    """
    operations = _extract_operations(openapi_spec)

    if not operations:
        return ""

    # Separate GET (read-only, safe) from write operations
    read_ops = [op for op in operations if op["http_method"] == "GET"]
    write_ops = [op for op in operations if op["http_method"] != "GET"]

    # --- Build test methods ---
    read_test_methods = _generate_read_tests(read_ops)
    write_test_methods = _generate_write_tests(write_ops)

    code = f'''"""
Generated Tool Call E2E Tests for {api_metadata.title}

Tests that actually invoke each MCP tool via tools/call over HTTP and verify
the response. Requires a running MCP server.

Coverage:
- {len(read_ops)} read-only tools (GET) — verified for successful response
- {len(write_ops)} write tools (POST/PUT/DELETE) — verified for MCP-level response

Generated by mcp_generator - DO NOT EDIT MANUALLY
"""

import json
import os

import httpx
import pytest

MCP_URL = os.getenv("MCP_SERVER_URL", "http://localhost:8000/mcp")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _parse_sse(text: str) -> dict | None:
    """Extract the JSON-RPC result from an SSE stream, skipping notifications."""
    for line in text.splitlines():
        if line.startswith("data: "):
            try:
                msg = json.loads(line[6:])
            except json.JSONDecodeError:
                continue
            # Skip server notifications (they have "method" but no "id")
            if "method" in msg and "id" not in msg:
                continue
            return msg
    return None


async def _mcp_call(client: httpx.AsyncClient, tool_name: str, arguments: dict,
                     *, session_id: str | None = None) -> dict:
    """Send a tools/call request and return the parsed JSON-RPC response."""
    headers = {{
        "Content-Type": "application/json",
        "Accept": "application/json, text/event-stream",
    }}
    if session_id:
        headers["mcp-session-id"] = session_id

    response = await client.post(
        MCP_URL,
        json={{
            "jsonrpc": "2.0",
            "id": f"call-{{tool_name}}",
            "method": "tools/call",
            "params": {{"name": tool_name, "arguments": arguments}},
        }},
        headers=headers,
    )

    assert response.status_code == 200, (
        f"tools/call {{tool_name}} returned HTTP {{response.status_code}}: {{response.text[:200]}}"
    )

    content_type = response.headers.get("content-type", "")
    if "text/event-stream" in content_type:
        data = _parse_sse(response.text)
        assert data is not None, (
            f"No JSON-RPC result in SSE stream for {{tool_name}}.\n"
            f"SSE body (first 500 chars): {{response.text[:500]}}"
        )
        return data

    return response.json()


async def _init_session(client: httpx.AsyncClient) -> str | None:
    """Perform MCP handshake and return session ID."""
    resp = await client.post(
        MCP_URL,
        json={{
            "jsonrpc": "2.0",
            "id": "init",
            "method": "initialize",
            "params": {{
                "protocolVersion": "2025-03-26",
                "capabilities": {{}},
                "clientInfo": {{"name": "e2e-tool-calls", "version": "1.0"}},
            }},
        }},
        headers={{
            "Content-Type": "application/json",
            "Accept": "application/json, text/event-stream",
        }},
    )
    session_id = resp.headers.get("mcp-session-id")

    # Complete handshake
    headers = {{"Content-Type": "application/json", "Accept": "application/json, text/event-stream"}}
    if session_id:
        headers["mcp-session-id"] = session_id
    await client.post(
        MCP_URL,
        json={{"jsonrpc": "2.0", "method": "notifications/initialized"}},
        headers=headers,
    )
    return session_id


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
async def mcp_session():
    """Create an initialized MCP session."""
    async with httpx.AsyncClient(timeout=60.0) as client:
        # Check server is up
        try:
            await client.post(
                MCP_URL,
                json={{"jsonrpc": "2.0", "id": "ping", "method": "ping"}},
                headers={{"Content-Type": "application/json", "Accept": "application/json, text/event-stream"}},
            )
        except httpx.ConnectError:
            pytest.skip(f"MCP server not available at {{MCP_URL}}")

        session_id = await _init_session(client)
        yield client, session_id


# ---------------------------------------------------------------------------
# Read-only tool tests (GET endpoints)
# ---------------------------------------------------------------------------

class TestReadToolCalls:
    """Test tools/call for read-only (GET) endpoints."""

{read_test_methods}


# ---------------------------------------------------------------------------
# Write tool tests (POST/PUT/DELETE endpoints)
# ---------------------------------------------------------------------------

class TestWriteToolCalls:
    """Test tools/call for write (POST/PUT/DELETE) endpoints.

    These tests verify the tool responds via MCP protocol. The backend may
    return 4xx errors (e.g. invalid payload) which is expected — we verify
    the MCP layer handles it correctly.
    """

{write_test_methods}
'''
    return code


def _generate_read_tests(operations: list[dict[str, Any]]) -> str:
    """Generate test methods for read-only tools."""
    if not operations:
        return "    pass  # No GET endpoints\n"

    methods: list[str] = []
    for op in operations:
        tool = op["tool_name"]
        summary = op["summary"].replace('"', '\\"')

        # Build arguments dict
        args_parts: list[str] = []
        for p in op["parameters"]:
            if p["required"] or p["in"] == "path":
                args_parts.append(f'"{p["name"]}": {_example_value(p)}')

        args_str = "{" + ", ".join(args_parts) + "}" if args_parts else "{}"

        method_name = camel_to_snake(op["operation_id"])

        methods.append(
            f'''    @pytest.mark.asyncio
    async def test_call_{method_name}(self, mcp_session):
        """{summary}"""
        client, session_id = mcp_session
        result = await _mcp_call(client, "{tool}", {args_str}, session_id=session_id)

        # Verify JSON-RPC response structure
        assert "result" in result or "error" in result, (
            f"Response missing both result and error: {{result}}"
        )

        if "result" in result:
            content = result["result"].get("content", [])
            assert len(content) > 0, "tools/call returned empty content"
            # Verify content has text
            assert any(c.get("text") for c in content), (
                f"No text content in response: {{content}}"
            )
            print(f"\\n✓ {tool}: got {{len(content)}} content block(s)")
        else:
            # Error response is acceptable for read tools that need auth or
            # specific data — but the MCP layer must still respond correctly
            error = result["error"]
            assert "message" in error, f"Error missing message: {{error}}"
            print(f"\\n⚠ {tool}: error (expected if auth required): {{error.get('message', '')[:100]}}")
'''
        )

    return "\n".join(methods)


def _generate_write_tests(operations: list[dict[str, Any]]) -> str:
    """Generate test methods for write tools."""
    if not operations:
        return "    pass  # No write endpoints\n"

    methods: list[str] = []
    for op in operations:
        tool = op["tool_name"]
        http_method = op["http_method"]
        summary = op["summary"].replace('"', '\\"')

        # Build arguments — include required params + minimal body
        args_parts: list[str] = []
        for p in op["parameters"]:
            if p["required"] or p["in"] == "path":
                args_parts.append(f'"{p["name"]}": {_example_value(p)}')

        if op["has_body"]:
            args_parts.append('"body": "{}"')

        args_str = "{" + ", ".join(args_parts) + "}" if args_parts else "{}"

        method_name = camel_to_snake(op["operation_id"])

        methods.append(
            f'''    @pytest.mark.asyncio
    async def test_call_{method_name}(self, mcp_session):
        """{http_method}: {summary}"""
        client, session_id = mcp_session
        result = await _mcp_call(client, "{tool}", {args_str}, session_id=session_id)

        # Write tools may fail at the backend (4xx) — that's OK.
        # We verify the MCP protocol layer responded correctly.
        assert "result" in result or "error" in result, (
            f"Response missing both result and error: {{result}}"
        )

        if "result" in result:
            content = result["result"].get("content", [])
            assert len(content) > 0, "{tool} returned empty content"
            print(f"\\n✓ {tool} ({http_method}): got {{len(content)}} content block(s)")
        else:
            # Backend errors are expected for write tools with dummy data
            error = result["error"]
            assert "message" in error, f"Error missing message: {{error}}"
            print(f"\\n⚠ {tool} ({http_method}): backend error (expected): {{error.get('message', '')[:100]}}")
'''
        )

    return "\n".join(methods)
