"""
Curated Display Tools for MCP Apps.

API-agnostic display tools that the LLM fills with data from any API response.
These provide interactive UI rendering (tables, charts, detail views, forms)
without requiring API-specific code generation.

Requires: pip install "fastmcp[apps]" (installs prefab-ui)

Auto-generated by mcp_generator.
"""

import logging
from typing import Any

from fastmcp import FastMCP

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Conditional Prefab imports — graceful fallback when prefab-ui is not installed
# ---------------------------------------------------------------------------
try:
    from prefab_ui.app import PrefabApp
    from prefab_ui.components import (
        Badge,
        Button,
        Column,
        DataTable,
        DataTableColumn,
        ForEach,
        Form,
        Heading,
        Input,
        Muted,
        Row,
        Separator,
        Text,
    )
    from prefab_ui.components.charts import BarChart, ChartSeries, LineChart
    from prefab_ui.actions import SetState, ShowToast
    from prefab_ui.actions.mcp import CallTool
    from prefab_ui.rx import RESULT

    PREFAB_AVAILABLE = True
except ImportError:
    PREFAB_AVAILABLE = False
    logger.warning(
        "prefab-ui not installed. Display tools will return JSON fallback. "
        "Install with: pip install 'fastmcp[apps]'"
    )

# Create the display tools server
mcp = FastMCP("DisplayTools")


# =============================================================================
# show_table — Tabular data display
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags=["display"],
    description="Display data as an interactive, sortable table.",
)
def show_table(
    title: str,
    columns: list[dict[str, str]],
    rows: list[dict[str, Any]],
) -> Any:
    """Display data as an interactive table.

    Args:
        title: Table heading.
        columns: Column definitions, each with 'key' and 'label'.
                 Example: [{"key": "id", "label": "ID"}, {"key": "name", "label": "Name"}]
        rows: Row data as list of dicts matching column keys.
              Example: [{"id": 1, "name": "Buddy"}, {"id": 2, "name": "Max"}]
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "columns": columns, "rows": rows}

    with Column(gap=4, css_class="p-6") as view:
        Heading(title)
        DataTable(
            rows=rows,
            columns=[DataTableColumn(key=c["key"], header=c.get("label", c["key"])) for c in columns],
        )

    return PrefabApp(view=view)


# =============================================================================
# show_detail — Key-value detail view
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags=["display"],
    description="Display a single record as a key-value detail card.",
)
def show_detail(
    title: str,
    fields: list[dict[str, Any]],
) -> Any:
    """Display a record as a key-value detail card.

    Args:
        title: Card heading.
        fields: Field definitions, each with 'label' and 'value'.
                Optional 'variant' for Badge styling ('default', 'outline', 'success', 'warning', 'error').
                Example: [{"label": "Name", "value": "Buddy"}, {"label": "Status", "value": "available", "variant": "success"}]
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "fields": fields}

    with Column(gap=4, css_class="p-6") as view:
        Heading(title)
        for field in fields:
            with Row(gap=3, align="center"):
                Text(str(field["label"]), css_class="font-medium text-muted-foreground w-32")
                variant = field.get("variant")
                if variant:
                    Badge(str(field["value"]), variant=variant)
                else:
                    Text(str(field["value"]))

    return PrefabApp(view=view)


# =============================================================================
# show_chart — Bar or line chart
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags=["display"],
    description="Display data as a bar or line chart.",
)
def show_chart(
    title: str,
    data: list[dict[str, Any]],
    x_axis: str,
    y_axes: list[dict[str, str]],
    chart_type: str = "bar",
) -> Any:
    """Display data as an interactive chart.

    Args:
        title: Chart heading.
        data: Data points as list of dicts.
              Example: [{"month": "Jan", "revenue": 42000, "cost": 31000}]
        x_axis: Key in data to use as X axis (e.g. "month").
        y_axes: Series definitions, each with 'key' and 'label'.
                Example: [{"key": "revenue", "label": "Revenue"}, {"key": "cost", "label": "Cost"}]
        chart_type: 'bar' or 'line' (default: 'bar').
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "chart_type": chart_type, "data": data, "x_axis": x_axis, "y_axes": y_axes}

    series = [ChartSeries(data_key=y["key"], label=y.get("label", y["key"])) for y in y_axes]
    ChartClass = LineChart if chart_type == "line" else BarChart

    with Column(gap=4, css_class="p-6") as view:
        Heading(title)
        ChartClass(data=data, series=series, x_axis=x_axis)

    return PrefabApp(view=view)


# =============================================================================
# show_form — Dynamic form that calls back into a tool
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags=["display"],
    description="Display a dynamic form that submits data to another tool.",
)
def show_form(
    title: str,
    fields: list[dict[str, Any]],
    submit_tool: str,
    submit_label: str = "Submit",
) -> Any:
    """Display a form that submits its values to another MCP tool.

    Args:
        title: Form heading.
        fields: Input field definitions, each with 'name', 'label', and optional 'required' (bool),
                'type' ('text', 'number', 'email'), 'placeholder'.
                Example: [{"name": "email", "label": "Email", "required": true, "type": "email"}]
        submit_tool: Name of the MCP tool to call on form submission.
        submit_label: Button text (default: 'Submit').
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "fields": fields, "submit_tool": submit_tool}

    with Column(gap=4, css_class="p-6") as view:
        Heading(title)
        with Form(
            on_submit=CallTool(
                submit_tool,
                on_success=ShowToast("Success!", variant="success"),
                on_error=ShowToast("Something went wrong", variant="error"),
            )
        ):
            for f in fields:
                Input(
                    name=f["name"],
                    label=f.get("label", f["name"]),
                    required=f.get("required", False),
                    placeholder=f.get("placeholder", ""),
                )
            Button(submit_label)

    return PrefabApp(view=view)


# =============================================================================
# show_comparison — Side-by-side comparison
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags=["display"],
    description="Display a side-by-side comparison of items.",
)
def show_comparison(
    title: str,
    items: list[dict[str, Any]],
    highlight_key: str | None = None,
) -> Any:
    """Display items side-by-side for comparison.

    Args:
        title: Comparison heading.
        items: List of items to compare. Each item is a dict with the same keys.
               Example: [{"name": "Plan A", "price": "$10", "storage": "5GB"},
                         {"name": "Plan B", "price": "$20", "storage": "50GB"}]
        highlight_key: Optional key whose value gets a colored Badge for emphasis.
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "items": items, "highlight_key": highlight_key}

    if not items:
        with Column(gap=4, css_class="p-6") as view:
            Heading(title)
            Muted("No items to compare.")
        return PrefabApp(view=view)

    # Use keys from the first item as the row labels
    keys = list(items[0].keys())

    with Column(gap=4, css_class="p-6") as view:
        Heading(title)
        # Header row with item identifiers
        with Row(gap=4):
            Text("", css_class="w-32")  # spacer for label column
            for item in items:
                first_val = str(item.get(keys[0], ""))
                Heading(first_val, level=4, css_class="flex-1 text-center")

        Separator()

        # Data rows
        for key in keys[1:]:
            with Row(gap=4, align="center"):
                Text(key, css_class="font-medium text-muted-foreground w-32")
                for item in items:
                    val = str(item.get(key, ""))
                    if key == highlight_key:
                        Badge(val, variant="outline", css_class="flex-1 text-center")
                    else:
                        Text(val, css_class="flex-1 text-center")

    return PrefabApp(view=view)
