"""
Curated Display Tools for MCP Apps.

API-agnostic display tools that the LLM fills with data from any API response.
These provide interactive UI rendering (tables, charts, detail views, forms)
without requiring API-specific code generation.

Requires: pip install "fastmcp[apps]" (installs prefab-ui)

Auto-generated by mcp_generator.
"""

import logging
from typing import Any

from fastmcp import FastMCP

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Conditional Prefab imports — graceful fallback when prefab-ui is not installed
# ---------------------------------------------------------------------------
try:
    from prefab_ui.actions import SetState, ShowToast
    from prefab_ui.actions.mcp import CallTool
    from prefab_ui.app import PrefabApp
    from prefab_ui.components import (
        Badge,
        Button,
        Card,
        CardContent,
        CardHeader,
        Column,
        DataTable,
        DataTableColumn,
        Dot,
        Form,
        Grid,
        Heading,
        Input,
        Metric,
        Muted,
        Progress,
        Row,
        Select,
        SelectOption,
        Separator,
        Small,
        Text,
    )
    from prefab_ui.components.charts import (
        AreaChart,
        BarChart,
        ChartSeries,
        LineChart,
        PieChart,
        Sparkline,
    )

    PREFAB_AVAILABLE = True
except ImportError:
    PREFAB_AVAILABLE = False
    logger.warning(
        "prefab-ui not installed. Display tools will return JSON fallback. "
        "Install with: pip install 'fastmcp[apps]'"
    )

# Create the display tools server
mcp = FastMCP("DisplayTools")


# =============================================================================
# show_table — Tabular data display
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags={"display"},
    description="Display data as an interactive, sortable, searchable table.",
)
def show_table(
    title: str,
    columns: list[dict[str, str]],
    rows: list[dict[str, Any]],
    subtitle: str = "",
) -> Any:
    """Display data as an interactive table with sorting and search.

    Args:
        title: Table heading.
        columns: Column definitions, each with 'key' and 'label'.
                 Optional 'sortable' (bool, default true).
                 Example: [{"key": "id", "label": "ID"}, {"key": "name", "label": "Name"}]
        rows: Row data as list of dicts matching column keys.
              Example: [{"id": 1, "name": "Buddy"}, {"id": 2, "name": "Max"}]
        subtitle: Optional description shown below the heading.
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "columns": columns, "rows": rows}

    with Column(gap=5, css_class="p-6 max-w-4xl") as view:
        Heading(title)
        if subtitle:
            Muted(subtitle)
        with Row(gap=2, align="center"):
            Badge(f"{len(rows)} records", variant="outline")
        DataTable(
            rows=rows,
            columns=[
                DataTableColumn(
                    key=c["key"],
                    header=c.get("label", c["key"]),
                    sortable=c.get("sortable", True),
                )
                for c in columns
            ],
            search=True,
        )

    return PrefabApp(view=view)


# =============================================================================
# show_detail — Key-value detail view
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags={"display"},
    description="Display a single record as a professional key-value detail card.",
)
def show_detail(
    title: str,
    fields: list[dict[str, Any]],
    subtitle: str = "",
) -> Any:
    """Display a record as a key-value detail card with badges for highlighted values.

    Args:
        title: Card heading.
        fields: Field definitions, each with 'label' and 'value'.
                Optional 'variant' for Badge styling ('default', 'outline', 'success', 'warning', 'error').
                Example: [{"label": "Name", "value": "Buddy"}, {"label": "Status", "value": "available", "variant": "success"}]
        subtitle: Optional description shown below the heading.
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "fields": fields}

    with Column(gap=5, css_class="p-6 max-w-2xl") as view:
        Heading(title)
        if subtitle:
            Muted(subtitle)
        with Card():
            with CardContent(css_class="py-4"):
                for i, fld in enumerate(fields):
                    with Row(gap=4, align="center", css_class="py-2"):
                        Text(
                            str(fld["label"]),
                            css_class="font-medium text-muted-foreground w-40 shrink-0",
                        )
                        variant = fld.get("variant")
                        if variant:
                            Badge(str(fld["value"]), variant=variant)
                        else:
                            Text(str(fld["value"]), css_class="font-medium")
                    if i < len(fields) - 1:
                        Separator()

    return PrefabApp(view=view)


# =============================================================================
# show_chart — Bar or line chart
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags={"display"},
    description="Display data as a bar, line, area, or pie chart with legend.",
)
def show_chart(
    title: str,
    data: list[dict[str, Any]],
    x_axis: str,
    y_axes: list[dict[str, str]],
    chart_type: str = "bar",
    subtitle: str = "",
) -> Any:
    """Display data as an interactive chart with multiple series support.

    Args:
        title: Chart heading.
        data: Data points as list of dicts.
              Example: [{"month": "Jan", "revenue": 42000, "cost": 31000}]
        x_axis: Key in data to use as X axis (e.g. "month").
        y_axes: Series definitions, each with 'key' and 'label'.
                Example: [{"key": "revenue", "label": "Revenue"}, {"key": "cost", "label": "Cost"}]
        chart_type: 'bar', 'line', 'area', or 'pie' (default: 'bar').
        subtitle: Optional description shown below the heading.
    """
    if not PREFAB_AVAILABLE:
        return {
            "title": title,
            "chart_type": chart_type,
            "data": data,
            "x_axis": x_axis,
            "y_axes": y_axes,
        }

    chart_classes = {"bar": BarChart, "line": LineChart, "area": AreaChart, "pie": PieChart}
    ChartClass = chart_classes.get(chart_type, BarChart)

    with Column(gap=5, css_class="p-6 max-w-4xl") as view:
        Heading(title)
        if subtitle:
            Muted(subtitle)
        with Card():
            with CardContent(css_class="pt-4"):
                if chart_type == "pie":
                    # PieChart uses data_key (numeric) + name_key (label) instead of series/x_axis
                    data_key = y_axes[0]["key"] if y_axes else "value"
                    PieChart(data=data, data_key=data_key, name_key=x_axis, show_legend=True)
                else:
                    series = [
                        ChartSeries(data_key=y["key"], label=y.get("label", y["key"]))
                        for y in y_axes
                    ]
                    ChartClass(data=data, series=series, x_axis=x_axis, show_legend=True)

    return PrefabApp(view=view)


# =============================================================================
# show_form — Dynamic form that calls back into a tool
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags={"display"},
    description="Display a dynamic form with validation that submits to another tool.",
)
def show_form(
    title: str,
    fields: list[dict[str, Any]],
    submit_tool: str,
    submit_label: str = "Submit",
    subtitle: str = "",
) -> Any:
    """Display a form that submits its values to another MCP tool.

    Args:
        title: Form heading.
        fields: Input field definitions, each with 'name', 'label', and optional:
                'required' (bool), 'type' ('text','number','email','select'),
                'placeholder', 'options' (list of strings — required when type is 'select').
                Example: [{"name": "email", "label": "Email", "required": true, "type": "email"},
                          {"name": "status", "label": "Status", "type": "select",
                           "options": ["available", "pending", "sold"]}]
        submit_tool: Name of the MCP tool to call on form submission.
        submit_label: Button text (default: 'Submit').
        subtitle: Optional description shown below the heading.
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "fields": fields, "submit_tool": submit_tool}

    from prefab_ui.rx import STATE

    # Wrap all form field values into a single 'data' dict so generated
    # tools receive them via their ``data: dict`` parameter.
    _data_payload = {f["name"]: "{{ " + f["name"] + " }}" for f in fields}

    with Column(gap=5, css_class="p-6 max-w-2xl") as view:
        Heading(title)
        if subtitle:
            Muted(subtitle)
        with Card():
            with CardContent(css_class="py-4"):
                with Form(
                    let={"submitting": False},
                    on_submit=[
                        SetState(key="submitting", value=True),
                        CallTool(
                            submit_tool,
                            arguments={"data": _data_payload},
                            on_success=[
                                SetState(key="submitting", value=False),
                                ShowToast("Submitted successfully!", variant="success"),
                            ],
                            on_error=[
                                SetState(key="submitting", value=False),
                                ShowToast("Something went wrong", variant="error"),
                            ],
                        ),
                    ],
                ):
                    with Column(gap=4):
                        for f in fields:
                            field_type = f.get("type", "text")
                            if field_type == "select" and f.get("options"):
                                with Select(
                                    name=f["name"],
                                    placeholder=f.get("placeholder", f.get("label", f["name"])),
                                    required=f.get("required", False),
                                ):
                                    for opt in f["options"]:
                                        SelectOption(
                                            label=opt
                                            if isinstance(opt, str)
                                            else opt.get("label", ""),
                                            value=opt
                                            if isinstance(opt, str)
                                            else opt.get("value", ""),
                                        )
                            else:
                                Input(
                                    name=f["name"],
                                    label=f.get("label", f["name"]),
                                    input_type=field_type,
                                    required=f.get("required", False),
                                    placeholder=f.get("placeholder", ""),
                                )
                        Button(submit_label, css_class="w-full", disabled=STATE.submitting)

    return PrefabApp(view=view)


# =============================================================================
# show_comparison — Side-by-side comparison
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags={"display"},
    description="Display a side-by-side comparison of items with highlights.",
)
def show_comparison(
    title: str,
    items: list[dict[str, Any]],
    highlight_key: str | None = None,
    subtitle: str = "",
) -> Any:
    """Display items side-by-side for comparison in individual cards.

    Args:
        title: Comparison heading.
        items: List of items to compare. Each item is a dict with the same keys.
               Example: [{"name": "Plan A", "price": "$10", "storage": "5GB"},
                         {"name": "Plan B", "price": "$20", "storage": "50GB"}]
        highlight_key: Optional key whose value gets a colored Badge for emphasis.
        subtitle: Optional description shown below the heading.
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "items": items, "highlight_key": highlight_key}

    if not items:
        with Column(gap=4, css_class="p-6") as view:
            Heading(title)
            Muted("No items to compare.")
        return PrefabApp(view=view)

    keys = list(items[0].keys())
    # Pick the best key for the card heading (name/title/label preferred, else first key)
    _title_candidates = ("name", "title", "label", "plan", "product", "option")
    name_key = next((k for k in keys if k.lower() in _title_candidates), keys[0])
    detail_keys = [k for k in keys if k != name_key]

    with Column(gap=5, css_class="p-6") as view:
        Heading(title)
        if subtitle:
            Muted(subtitle)
        with Grid(columns=len(items), gap=4):
            for item in items:
                with Card():
                    with CardHeader():
                        Heading(str(item.get(name_key, "")), level=3)
                    with CardContent():
                        for key in detail_keys:
                            with Row(gap=3, align="center", css_class="py-1"):
                                Muted(
                                    key, css_class="w-28 shrink-0 text-xs uppercase tracking-wide"
                                )
                                val = str(item.get(key, ""))
                                if key == highlight_key:
                                    Badge(val, variant="success")
                                else:
                                    Text(val, css_class="font-medium")

    return PrefabApp(view=view)


# =============================================================================
# show_metrics — KPI dashboard with optional sparklines
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags={"display"},
    description="Display key metrics as a dashboard grid with optional sparklines.",
)
def show_metrics(
    title: str,
    metrics: list[dict[str, Any]],
    columns: int = 4,
    subtitle: str = "",
) -> Any:
    """Display KPI metrics in a responsive grid layout.

    Args:
        title: Dashboard heading.
        metrics: Metric definitions, each with 'label' and 'value'.
                 Optional: 'delta' (str, e.g. "+5%"), 'trend' ("up"/"down"),
                 'trend_sentiment' ("positive"/"negative"/"neutral"),
                 'description' (str), 'sparkline' (list of numbers).
                 Example: [{"label": "Revenue", "value": "$42K", "delta": "+12%",
                            "trend": "up", "trend_sentiment": "positive",
                            "sparkline": [10, 25, 18, 30, 42]}]
        columns: Number of grid columns (default: 4).
        subtitle: Optional description shown below the heading.
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "metrics": metrics}

    with Column(gap=5, css_class="p-6") as view:
        Heading(title)
        if subtitle:
            Muted(subtitle)
        with Grid(columns=columns, gap=4):
            for m in metrics:
                with Card():
                    with CardContent(css_class="pt-4"):
                        Metric(
                            label=str(m["label"]),
                            value=str(m["value"]),
                            delta=m.get("delta"),
                            trend=m.get("trend"),
                            trend_sentiment=m.get("trend_sentiment"),
                            description=m.get("description"),
                        )
                        sparkline_data = m.get("sparkline")
                        if sparkline_data:
                            Sparkline(
                                data=sparkline_data,
                                variant="line",
                                fill=True,
                                curve="smooth",
                            )

    return PrefabApp(view=view)


# =============================================================================
# show_timeline — Chronological event feed
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags={"display"},
    description="Display events as a chronological timeline with status indicators.",
)
def show_timeline(
    title: str,
    events: list[dict[str, Any]],
    subtitle: str = "",
) -> Any:
    """Display a chronological timeline of events.

    Args:
        title: Timeline heading.
        events: Event entries, each with 'title' and 'timestamp'.
                Optional: 'description' (str), 'status' (str — mapped to dot color),
                'badge' (str — displayed as Badge), 'badge_variant' (str).
                Example: [{"title": "Order placed", "timestamp": "2026-04-20 10:30",
                           "status": "completed", "description": "Payment confirmed",
                           "badge": "Completed", "badge_variant": "success"}]
        subtitle: Optional description shown below the heading.
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "events": events}

    # Map status strings to dot colors
    dot_colors: dict[str, str] = {
        "completed": "green",
        "success": "green",
        "active": "blue",
        "in_progress": "blue",
        "pending": "yellow",
        "warning": "yellow",
        "error": "red",
        "failed": "red",
        "cancelled": "gray",
    }

    with Column(gap=5, css_class="p-6 max-w-3xl") as view:
        Heading(title)
        if subtitle:
            Muted(subtitle)
        with Card():
            with CardContent(css_class="py-4"):
                for i, event in enumerate(events):
                    status = str(event.get("status", "")).lower()
                    color = dot_colors.get(status, "gray")
                    with Row(gap=4, align="start", css_class="py-3"):
                        Dot(color=color, css_class="mt-1.5 shrink-0")
                        with Column(gap=1, css_class="flex-1"):
                            with Row(gap=2, align="center"):
                                Text(str(event["title"]), css_class="font-medium")
                                badge_text = event.get("badge")
                                if badge_text:
                                    Badge(
                                        str(badge_text),
                                        variant=event.get("badge_variant", "outline"),
                                    )
                            desc = event.get("description")
                            if desc:
                                Muted(str(desc))
                            Small(
                                str(event.get("timestamp", "")), css_class="text-muted-foreground"
                            )
                    if i < len(events) - 1:
                        Separator()

    return PrefabApp(view=view)


# =============================================================================
# show_progress — Multi-step status tracker
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags={"display"},
    description="Display a multi-step progress tracker with status indicators.",
)
def show_progress(
    title: str,
    steps: list[dict[str, str]],
    subtitle: str = "",
) -> Any:
    """Display a multi-step progress tracker.

    Args:
        title: Tracker heading.
        steps: Step definitions, each with 'label' and 'status'.
               Status: 'completed', 'active', 'pending'.
               Optional: 'description' (str).
               Example: [{"label": "Order Placed", "status": "completed"},
                         {"label": "Processing", "status": "active", "description": "Preparing shipment"},
                         {"label": "Shipped", "status": "pending"},
                         {"label": "Delivered", "status": "pending"}]
        subtitle: Optional description shown below the heading.
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "steps": steps}

    # Calculate overall progress percentage
    total = len(steps)
    completed_count = sum(1 for s in steps if s.get("status") == "completed")
    active_count = sum(1 for s in steps if s.get("status") == "active")
    progress_pct = int(((completed_count + active_count * 0.5) / max(total, 1)) * 100)

    status_config: dict[str, dict[str, str]] = {
        "completed": {"color": "green", "badge_variant": "success", "label": "Done"},
        "active": {"color": "blue", "badge_variant": "info", "label": "In Progress"},
        "pending": {"color": "gray", "badge_variant": "outline", "label": "Pending"},
    }

    with Column(gap=5, css_class="p-6 max-w-3xl") as view:
        Heading(title)
        if subtitle:
            Muted(subtitle)
        Progress(value=progress_pct, css_class="h-2")
        with Row(gap=2, align="center"):
            Badge(f"{completed_count}/{total} steps", variant="outline")
            Muted(f"{progress_pct}% complete")
        with Card():
            with CardContent(css_class="py-4"):
                for i, step in enumerate(steps):
                    status = step.get("status", "pending")
                    config = status_config.get(status, status_config["pending"])
                    with Row(gap=4, align="center", css_class="py-3"):
                        Dot(color=config["color"], css_class="shrink-0")
                        with Column(gap=0, css_class="flex-1"):
                            Text(str(step["label"]), css_class="font-medium")
                            desc = step.get("description")
                            if desc:
                                Muted(str(desc))
                        Badge(config["label"], variant=config["badge_variant"])
                    if i < len(steps) - 1:
                        Separator()

    return PrefabApp(view=view)
