"""
Curated Display Tools for MCP Apps.

API-agnostic display tools that the LLM fills with data from any API response.
These provide interactive UI rendering (tables, charts, detail views, forms)
without requiring API-specific code generation.

Requires: pip install "fastmcp[apps]" (installs prefab-ui)

Auto-generated by mcp_generator.
"""

import logging
from typing import Any

from fastmcp import FastMCP

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Conditional Prefab imports — graceful fallback when prefab-ui is not installed
# ---------------------------------------------------------------------------
try:
    from prefab_ui.app import PrefabApp
    from prefab_ui.components import (
        Badge,
        Button,
        Card,
        CardContent,
        CardHeader,
        Column,
        DataTable,
        DataTableColumn,
        ForEach,
        Form,
        Grid,
        Heading,
        Input,
        Metric,
        Muted,
        Row,
        Separator,
        Text,
    )
    from prefab_ui.components.charts import (
        AreaChart,
        BarChart,
        ChartSeries,
        LineChart,
        PieChart,
    )
    from prefab_ui.actions import SetState, ShowToast
    from prefab_ui.actions.mcp import CallTool
    from prefab_ui.rx import RESULT

    PREFAB_AVAILABLE = True
except ImportError:
    PREFAB_AVAILABLE = False
    logger.warning(
        "prefab-ui not installed. Display tools will return JSON fallback. "
        "Install with: pip install 'fastmcp[apps]'"
    )

# Create the display tools server
mcp = FastMCP("DisplayTools")


# =============================================================================
# show_table — Tabular data display
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags=["display"],
    description="Display data as an interactive, sortable, searchable table.",
)
def show_table(
    title: str,
    columns: list[dict[str, str]],
    rows: list[dict[str, Any]],
    subtitle: str = "",
) -> Any:
    """Display data as an interactive table with sorting and search.

    Args:
        title: Table heading.
        columns: Column definitions, each with 'key' and 'label'.
                 Optional 'sortable' (bool, default true).
                 Example: [{"key": "id", "label": "ID"}, {"key": "name", "label": "Name"}]
        rows: Row data as list of dicts matching column keys.
              Example: [{"id": 1, "name": "Buddy"}, {"id": 2, "name": "Max"}]
        subtitle: Optional description shown below the heading.
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "columns": columns, "rows": rows}

    with Column(gap=5, css_class="p-6 max-w-4xl") as view:
        Heading(title)
        if subtitle:
            Muted(subtitle)
        with Row(gap=2, align="center"):
            Badge(f"{len(rows)} records", variant="outline")
        DataTable(
            rows=rows,
            columns=[
                DataTableColumn(
                    key=c["key"],
                    header=c.get("label", c["key"]),
                    sortable=c.get("sortable", True),
                )
                for c in columns
            ],
            search=True,
        )

    return PrefabApp(view=view)


# =============================================================================
# show_detail — Key-value detail view
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags=["display"],
    description="Display a single record as a professional key-value detail card.",
)
def show_detail(
    title: str,
    fields: list[dict[str, Any]],
    subtitle: str = "",
) -> Any:
    """Display a record as a key-value detail card with badges for highlighted values.

    Args:
        title: Card heading.
        fields: Field definitions, each with 'label' and 'value'.
                Optional 'variant' for Badge styling ('default', 'outline', 'success', 'warning', 'error').
                Example: [{"label": "Name", "value": "Buddy"}, {"label": "Status", "value": "available", "variant": "success"}]
        subtitle: Optional description shown below the heading.
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "fields": fields}

    with Column(gap=5, css_class="p-6 max-w-2xl") as view:
        Heading(title)
        if subtitle:
            Muted(subtitle)
        with Card():
            with CardContent(css_class="py-4"):
                for i, fld in enumerate(fields):
                    with Row(gap=4, align="center", css_class="py-2"):
                        Text(
                            str(fld["label"]),
                            css_class="font-medium text-muted-foreground w-40 shrink-0",
                        )
                        variant = fld.get("variant")
                        if variant:
                            Badge(str(fld["value"]), variant=variant)
                        else:
                            Text(str(fld["value"]), css_class="font-medium")
                    if i < len(fields) - 1:
                        Separator()

    return PrefabApp(view=view)


# =============================================================================
# show_chart — Bar or line chart
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags=["display"],
    description="Display data as a bar, line, area, or pie chart with legend.",
)
def show_chart(
    title: str,
    data: list[dict[str, Any]],
    x_axis: str,
    y_axes: list[dict[str, str]],
    chart_type: str = "bar",
    subtitle: str = "",
) -> Any:
    """Display data as an interactive chart with multiple series support.

    Args:
        title: Chart heading.
        data: Data points as list of dicts.
              Example: [{"month": "Jan", "revenue": 42000, "cost": 31000}]
        x_axis: Key in data to use as X axis (e.g. "month").
        y_axes: Series definitions, each with 'key' and 'label'.
                Example: [{"key": "revenue", "label": "Revenue"}, {"key": "cost", "label": "Cost"}]
        chart_type: 'bar', 'line', 'area', or 'pie' (default: 'bar').
        subtitle: Optional description shown below the heading.
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "chart_type": chart_type, "data": data, "x_axis": x_axis, "y_axes": y_axes}

    chart_classes = {"bar": BarChart, "line": LineChart, "area": AreaChart, "pie": PieChart}
    ChartClass = chart_classes.get(chart_type, BarChart)
    series = [ChartSeries(data_key=y["key"], label=y.get("label", y["key"])) for y in y_axes]

    with Column(gap=5, css_class="p-6 max-w-4xl") as view:
        Heading(title)
        if subtitle:
            Muted(subtitle)
        with Card():
            with CardContent(css_class="pt-4"):
                ChartClass(data=data, series=series, x_axis=x_axis, show_legend=True)

    return PrefabApp(view=view)


# =============================================================================
# show_form — Dynamic form that calls back into a tool
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags=["display"],
    description="Display a dynamic form with validation that submits to another tool.",
)
def show_form(
    title: str,
    fields: list[dict[str, Any]],
    submit_tool: str,
    submit_label: str = "Submit",
    subtitle: str = "",
) -> Any:
    """Display a form that submits its values to another MCP tool.

    Args:
        title: Form heading.
        fields: Input field definitions, each with 'name', 'label', and optional 'required' (bool),
                'type' ('text', 'number', 'email'), 'placeholder'.
                Example: [{"name": "email", "label": "Email", "required": true, "type": "email"}]
        submit_tool: Name of the MCP tool to call on form submission.
        submit_label: Button text (default: 'Submit').
        subtitle: Optional description shown below the heading.
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "fields": fields, "submit_tool": submit_tool}

    with Column(gap=5, css_class="p-6 max-w-2xl") as view:
        Heading(title)
        if subtitle:
            Muted(subtitle)
        with Card():
            with CardContent(css_class="py-4"):
                with Form(
                    on_submit=CallTool(
                        submit_tool,
                        on_success=ShowToast("Success!", variant="success"),
                        on_error=ShowToast("Something went wrong", variant="error"),
                    )
                ):
                    with Column(gap=4):
                        for f in fields:
                            Input(
                                name=f["name"],
                                label=f.get("label", f["name"]),
                                required=f.get("required", False),
                                placeholder=f.get("placeholder", ""),
                            )
                        Button(submit_label, css_class="w-full")

    return PrefabApp(view=view)


# =============================================================================
# show_comparison — Side-by-side comparison
# =============================================================================


@mcp.tool(
    app=True if PREFAB_AVAILABLE else False,
    tags=["display"],
    description="Display a side-by-side comparison of items with highlights.",
)
def show_comparison(
    title: str,
    items: list[dict[str, Any]],
    highlight_key: str | None = None,
    subtitle: str = "",
) -> Any:
    """Display items side-by-side for comparison in individual cards.

    Args:
        title: Comparison heading.
        items: List of items to compare. Each item is a dict with the same keys.
               Example: [{"name": "Plan A", "price": "$10", "storage": "5GB"},
                         {"name": "Plan B", "price": "$20", "storage": "50GB"}]
        highlight_key: Optional key whose value gets a colored Badge for emphasis.
        subtitle: Optional description shown below the heading.
    """
    if not PREFAB_AVAILABLE:
        return {"title": title, "items": items, "highlight_key": highlight_key}

    if not items:
        with Column(gap=4, css_class="p-6") as view:
            Heading(title)
            Muted("No items to compare.")
        return PrefabApp(view=view)

    keys = list(items[0].keys())
    # First key is used as the card heading
    name_key = keys[0]
    detail_keys = keys[1:]

    with Column(gap=5, css_class="p-6") as view:
        Heading(title)
        if subtitle:
            Muted(subtitle)
        with Grid(columns=len(items), gap=4):
            for item in items:
                with Card():
                    with CardHeader():
                        Heading(str(item.get(name_key, "")), level=3)
                    with CardContent():
                        for key in detail_keys:
                            with Row(gap=3, align="center", css_class="py-1"):
                                Muted(key, css_class="w-28 shrink-0 text-xs uppercase tracking-wide")
                                val = str(item.get(key, ""))
                                if key == highlight_key:
                                    Badge(val, variant="success")
                                else:
                                    Text(val, css_class="font-medium")

    return PrefabApp(view=view)
