"""
Template generation for Dockerfile and related Docker files.

Generates Docker configuration files for the generated MCP server.
"""

from ..models import ApiMetadata


def generate_dockerfile(api_metadata: ApiMetadata, server_name: str) -> str:
    """Generate a Dockerfile for the MCP server."""

    return f"""# Dockerfile for {api_metadata.title} MCP Server
# Auto-generated by mcp_generator
# Multi-stage build for optimized production image

# Stage 1: Build stage
FROM python:3.11-slim AS builder

WORKDIR /build

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    git \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY pyproject.toml README.md ./
COPY {server_name}_mcp_generated.py ./
COPY servers/ ./servers/
COPY middleware/ ./middleware/

# Install Python dependencies
RUN pip install --no-cache-dir --upgrade pip && \\
    pip install --no-cache-dir -e .

# Stage 2: Runtime stage
FROM python:3.11-slim

LABEL maintainer="{api_metadata.contact.get("email", "your-email@example.com")}"
LABEL description="{api_metadata.description}"
LABEL version="{api_metadata.version}"

WORKDIR /app

# Copy Python packages from builder
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# Copy application code
COPY {server_name}_mcp_generated.py ./
COPY servers/ ./servers/
COPY middleware/ ./middleware/
COPY pyproject.toml README.md ./

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV API_BASE_URL={api_metadata.backend_url}

# Create non-root user
RUN useradd -m -u 1000 mcpuser && chown -R mcpuser:mcpuser /app
USER mcpuser

# Expose port for HTTP transport
EXPOSE 8000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
    CMD python -c "import sys; sys.exit(0)" || exit 1

# Default: Run in HTTP mode
ENTRYPOINT ["python", "{server_name}_mcp_generated.py"]
CMD ["--transport", "http", "--host", "0.0.0.0", "--port", "8000"]

# Usage examples:
#
# Build:
#   docker build -t {server_name}-mcp .
#
# Run in HTTP mode (default):
#   docker run -p 8000:8000 -e API_TOKEN=your-token {server_name}-mcp
#
# Run in HTTP mode with JWT validation:
#   docker run -p 8000:8000 {server_name}-mcp --validate-tokens
#
# Run in STDIO mode (for local testing):
#   docker run -i -e API_TOKEN=your-token {server_name}-mcp --transport stdio
#
# Override backend URL:
#   docker run -p 8000:8000 -e API_BASE_URL=https://api.example.com {server_name}-mcp
#
# With docker-compose (see docker-compose.yml):
#   docker-compose up
"""


def generate_docker_compose(api_metadata: ApiMetadata, server_name: str) -> str:
    """Generate a docker-compose.yml for the MCP server."""

    return f"""# docker-compose.yml for {api_metadata.title} MCP Server
# Auto-generated by mcp_generator

version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: {server_name}-mcp:latest
    container_name: {server_name}-mcp
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      # Backend API configuration
      API_BASE_URL: {api_metadata.backend_url}
      API_TOKEN: ${{API_TOKEN}}  # Set in .env file

      # Python settings
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"

      # Optional: JWT validation (uncomment to enable)
      # JWKS_URL: https://your-auth-server.com/.well-known/jwks.json

    # Override default command if needed
    # command: ["--transport", "http", "--host", "0.0.0.0", "--port", "8000", "--validate-tokens"]

    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8000/health', timeout=3)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Network (optional - for connecting to other services)
    # networks:
    #   - mcp-network

# Optional: Define custom network
# networks:
#   mcp-network:
#     driver: bridge

# Usage:
#   1. Create .env file with: API_TOKEN=your-token
#   2. Run: docker-compose up -d
#   3. View logs: docker-compose logs -f
#   4. Stop: docker-compose down
"""


def generate_dockerignore() -> str:
    """Generate a .dockerignore file for the MCP server."""

    return """# .dockerignore for MCP Server
# Auto-generated by mcp_generator

# Python cache
__pycache__/
*.py[cod]
*$py.class
*.so
.Python

# Virtual environments
.venv/
venv/
ENV/
env/

# Testing
.pytest_cache/
.coverage
htmlcov/
.mypy_cache/
.ruff_cache/
*.log

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Git
.git/
.gitignore
.gitattributes

# Build artifacts
build/
dist/
*.egg-info/

# Documentation (don't need in container)
docs/
*.md
!README.md

# Test files (don't need in production)
test/
tests/
*_test.py
test_*.py

# CI/CD
.github/
.gitlab-ci.yml
.travis.yml

# Docker
Dockerfile
docker-compose.yml
.dockerignore

# Keys and secrets (never include!)
keys/
*.pem
*.key
.env
.env.*
"""
