"""
MCP Generator - Core orchestration.

Main generator functions that coordinate introspection, rendering, and writing.
"""

from pathlib import Path

from .introspection import (
    get_api_metadata,
    get_api_modules,
    get_resource_endpoints,
    get_security_config,
)
from .models import ApiMetadata, ModuleSpec, SecurityConfig
from .renderers import generate_server_module


def generate_modular_servers(
    base_dir: Path | None = None, enable_resources: bool = False
) -> tuple[dict[str, ModuleSpec], int]:
    """Generate modular MCP servers from API client classes.

    Args:
        base_dir: Base directory containing generated_openapi. Defaults to current working directory.
        enable_resources: Generate MCP resource templates from GET endpoints

    Returns:
        tuple[dict[str, ModuleSpec], int]: (dict of modules keyed by module_name, total_tool_count)
    """
    if base_dir is None:
        base_dir = Path.cwd()

    # Get API modules dynamically (sort keys for deterministic output)
    api_modules = get_api_modules(base_dir)

    # Get resource endpoints if enabled
    resources_by_tag = {}
    if enable_resources:
        resources_by_tag = get_resource_endpoints(base_dir)

    servers: dict[str, ModuleSpec] = {}
    total_tools = 0

    # Generate a server module for each API class. Key the resulting dict by
    # ModuleSpec.module_name (stable identifier) rather than filename to avoid
    # brittle filename-based lookups downstream.
    for api_var_name in sorted(api_modules.keys()):
        api_class = api_modules[api_var_name]

        # Find matching resource endpoints for this API by tag
        # Map api_var_name (e.g., 'pet_api') to tag (e.g., 'pet')
        tag_name = api_var_name.replace("_api", "")
        resource_endpoints = resources_by_tag.get(tag_name, [])

        module_spec = generate_server_module(api_var_name, api_class, resource_endpoints)
        servers[module_spec.module_name] = module_spec
        total_tools += module_spec.tool_count

    return servers, total_tools


def generate_main_composition_server(
    modules: dict[str, ModuleSpec],
    api_metadata: ApiMetadata,
    security_config: SecurityConfig,
    composition_strategy: str = "mount",
    resource_prefix_format: str = "path",
) -> str:
    """Generate main server that composes all modular servers.

    Generates code targeting **FastMCP 3.x**.

    Key FastMCP 3.x changes vs 2.x:
      - ``mount(prefix=...)`` → ``mount(namespace=...)``
      - ``import_server(...)`` is deprecated → use ``mount(...)``
      - ``ctx.get_state()`` / ``ctx.set_state()`` are now **async**
      - ``resource_prefix_format`` constructor kwarg removed
      - ``create_streamable_http_app(...)`` → ``mcp.http_app(...)``
      - ``InMemoryEventStore`` → ``EventStore`` from ``fastmcp.server.event_store``

    Args:
        modules: Dictionary of module specifications
        api_metadata: API metadata from OpenAPI spec
        security_config: Security configuration
        composition_strategy: "mount" (default, recommended for v3)
        resource_prefix_format: Ignored in v3 (kept for config compat)
    """
    module_names = sorted(modules.keys())
    total_tool_count = sum(spec.tool_count for spec in modules.values())

    # Build import statements using the actual generated filename from ModuleSpec
    imports = "\n".join(
        [
            f"from servers.{modules[name].filename.replace('.py', '')} import mcp as {name}_mcp"
            for name in module_names
        ]
    )

    # In FastMCP 3.x mount() is synchronous and the recommended approach.
    # import_server() is deprecated → always use mount(namespace=...).
    compositions = "\n    ".join(
        [f'app.mount({name}_mcp, namespace="{name}")' for name in module_names]
    )

    # Build comprehensive header
    header_lines = [
        '"""',
        f"{api_metadata.title} MCP Server - Main Composition.",
        "",
        f"{api_metadata.description}",
        f"Version: {api_metadata.version}",
    ]

    if api_metadata.contact and api_metadata.contact.get("email"):
        header_lines.append(f"Contact: {api_metadata.contact['email']}")
    if api_metadata.license and api_metadata.license.get("name"):
        header_lines.append(f"License: {api_metadata.license['name']}")
    if api_metadata.external_docs and api_metadata.external_docs.get("url"):
        header_lines.append(f"Documentation: {api_metadata.external_docs['url']}")

    header_lines.extend(
        [
            "",
            "This server composes all modular API servers into a unified MCP interface.",
            "Composition: mount() with namespace isolation (FastMCP 3.x)",
            "",
            "Auto-generated by mcp_generator.",
            "DO NOT EDIT MANUALLY - regenerate using: python -m mcp_generator",
            "Configuration: fastmcp.json",
            '"""',
        ]
    )

    header_doc = "\n".join(header_lines)

    # --- Authentication imports (always need middleware for openapi_client) ---
    auth_imports = """
# Import API client middleware (required even without authentication)
from middleware.authentication import ApiClientContextMiddleware
"""
    auth_middleware_setup = """
    app.add_middleware(ApiClientContextMiddleware(
        transport_mode=args.transport,
        validate_tokens=False  # Token validation is done at ASGI layer for HTTP
    ))"""
    auth_argparse = ""
    auth_validation = ""

    if security_config.has_authentication():
        auth_imports += """from middleware.oauth_provider import create_jwt_verifier, build_authentication_stack, RequireScopesMiddleware
"""
        auth_argparse = """
    parser.add_argument(
        "--validate-tokens",
        action="store_true",
        default=default_validate_tokens,
        help=f"Enable JWT token validation for HTTP transport (default: {{default_validate_tokens}}, configurable in fastmcp.json)"
    )
"""
        auth_validation = """
    # Validate that --validate-tokens only works with HTTP transport
    if args.validate_tokens and args.transport != "http":
        logger.warning("⚠️  --validate-tokens is only applicable for HTTP transport, ignoring for STDIO mode")
        args.validate_tokens = False
"""

    # --- HTTP token-validation block (only when auth is configured) ---
    if security_config.has_authentication():
        http_token_validation_block = """
        # For HTTP transport with token validation, use ASGI middleware
        if hasattr(args, 'validate_tokens') and args.validate_tokens:
            logger.info("  🔧 ASGI Middleware: Authentication (JWT validation) at HTTP layer")
            logger.info("  🔑 JWT validation: Enabled via Starlette auth backend + scope guard")

            # Create JWT verifier for token validation
            jwt_verifier = create_jwt_verifier()
            if jwt_verifier:
                asgi_middleware = build_authentication_stack(jwt_verifier, require_auth=True)

                from fastmcp.server.event_store import EventStore

                event_store = EventStore()
                http_app = app.http_app(
                    path="/mcp",
                    event_store=event_store,
                    middleware=asgi_middleware if asgi_middleware else None,
                )

                import uvicorn, anyio
                logger.info("  ✅ ASGI middleware configured with token enforcement")
                config = uvicorn.Config(http_app, host=args.host, port=args.port, log_level="info")
                uvicorn_server = uvicorn.Server(config)
                anyio.run(uvicorn_server.serve)
            else:
                logger.warning("  ⚠️ JWT verifier initialization failed - falling back to backend validation")
                app.run(transport="http", host=args.host, port=args.port)
        else:
            logger.info("  🔧 FastMCP Middleware: Error handling → Auth (backend validation) → Timing → Logging")
            app.run(transport="http", host=args.host, port=args.port)"""
    else:
        http_token_validation_block = """
        logger.info("  🔧 FastMCP Middleware: Error handling → Auth (backend validation) → Timing → Logging")
        app.run(transport="http", host=args.host, port=args.port)"""

    # --- Build the generated code ---
    code = f'''{header_doc}

import logging
import os
import sys
from pathlib import Path

from fastmcp import FastMCP
from fastmcp.server.middleware.timing import DetailedTimingMiddleware
from fastmcp.server.middleware.logging import LoggingMiddleware
from fastmcp.server.middleware.error_handling import ErrorHandlingMiddleware

# Add the src folder and generated folder to the Python path
src_path = Path(__file__).parent
generated_path = src_path.parent / "generated_openapi"
if str(src_path) not in sys.path:
    sys.path.insert(0, str(src_path))
if str(generated_path) not in sys.path:
    sys.path.insert(0, str(generated_path))

# Import all modular servers
{imports}{auth_imports}

logger = logging.getLogger(__name__)

# Create main FastMCP 3.x Server (using 'app' for fastmcp auto-detection)
app = FastMCP("{api_metadata.title}")


def _compose_mcp_servers():
    """Compose all modular servers into the main server.

    Uses mount(namespace=...) for composition (FastMCP 3.x).
    Changes to mounted subservers are immediately reflected.
    """
    try:
        print("🔗 Composing modular servers...")
    except UnicodeEncodeError:
        print("Composing modular servers...")
    {compositions}
    try:
        print(f"✅ Server composition complete - {total_tool_count} MCP tools registered")
    except UnicodeEncodeError:
        print(f"[OK] Server composition complete - {total_tool_count} MCP tools registered")


async def create_server() -> FastMCP:
    """
    Factory function for fastmcp CLI (run, dev, install, inspect).

    Composes all modular servers and returns the configured main server.
    This is the REQUIRED entrypoint for fastmcp commands.

    Usage:
        fastmcp dev server.py:create_server
        fastmcp run server.py:create_server
        fastmcp install claude-desktop server.py:create_server

    Returns:
        FastMCP: The fully composed and configured server instance
    """
    _compose_mcp_servers()
    return app


# API Metadata (extracted during generation)
API_TITLE = "{api_metadata.title}"
API_DESCRIPTION = """{api_metadata.description}"""
API_VERSION = "{api_metadata.version}"
TOTAL_TOOL_COUNT = {total_tool_count}

def main():
    """Run the FastMCP 3.x backend tools server."""
    import argparse
    import json
    from pathlib import Path

    # Try to load fastmcp.json for default configuration
    fastmcp_config = {{}}
    fastmcp_path = Path(__file__).parent / "fastmcp.json"
    if fastmcp_path.exists():
        try:
            with open(fastmcp_path, "r", encoding="utf-8") as f:
                fastmcp_config = json.load(f)
        except Exception as e:
            logger.warning(f"Could not load fastmcp.json: {{e}}")

    # Get default validate_tokens from config (handle both bool and string values)
    _raw_validate = fastmcp_config.get("middleware", {{}}).get("config", {{}}).get("authentication", {{}}).get("validate_tokens", False)
    default_validate_tokens = _raw_validate if isinstance(_raw_validate, bool) else str(_raw_validate).lower() not in ("false", "0", "no", "")

    # Build comprehensive description
    description_parts = [f"{{API_TITLE}} - FastMCP 3.x MCP Server"]
    if API_DESCRIPTION:
        description_parts.append(API_DESCRIPTION)
    if API_VERSION:
        description_parts.append(f"Version: {{API_VERSION}}")

    parser = argparse.ArgumentParser(
        description="\\n".join(description_parts),
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--transport",
        choices=["stdio", "http"],
        default="stdio",
        help="Transport protocol to use (default: stdio)"
    )
    parser.add_argument(
        "--host",
        default="0.0.0.0",
        help="Host to bind to for HTTP transport (default: 0.0.0.0)"
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8000,
        help="Port to bind to for HTTP transport (default: 8000)"
    )
{auth_argparse}
    args = parser.parse_args()
{auth_validation}
    # Add FastMCP middleware stack (order matters!)
    try:
        print("🔧 Configuring FastMCP middleware...")
    except UnicodeEncodeError:
        print("Configuring FastMCP middleware...")
    app.add_middleware(ErrorHandlingMiddleware(include_traceback=True))
{auth_middleware_setup}
    app.add_middleware(DetailedTimingMiddleware())
    app.add_middleware(LoggingMiddleware(include_payloads=False))
    try:
        print("✅ FastMCP middleware configured")
    except UnicodeEncodeError:
        print("[OK] FastMCP middleware configured")

    # Compose all servers
    _compose_mcp_servers()

    if args.transport == "stdio":
        logger.info("🚀 Starting FastMCP 3.x server with STDIO transport")
        logger.info("  🔐 Authentication: BACKEND_API_TOKEN environment variable")
        logger.info("  🔒 Token validation: N/A (STDIO mode - backend validates tokens)")
        logger.info(f"  📦 Modules: {len(module_names)} composed ({{TOTAL_TOOL_COUNT}} MCP tools)")
        logger.info("  🔧 Middleware: Error handling → Auth → Timing → Logging")
        app.run(transport="stdio")
    else:  # http
        logger.info(f"🚀 Starting FastMCP 3.x server with HTTP transport on {{args.host}}:{{args.port}}")
        logger.info("  🔐 Authentication: Bearer token in Authorization header")

        logger.info(f"  🔒 Token validation: {{'enabled (JWT)' if hasattr(args, 'validate_tokens') and args.validate_tokens else 'disabled (delegated to backend)'}}")
        logger.info(f"  📦 Modules: {len(module_names)} composed ({{TOTAL_TOOL_COUNT}} MCP tools)")
{http_token_validation_block}


if __name__ == "__main__":
    main()
'''

    return code


def generate_all(
    base_dir: Path | None = None, enable_resources: bool = False
) -> tuple[ApiMetadata, SecurityConfig, dict[str, ModuleSpec], int]:
    """
    Main entry point for generating all MCP server components.

    Args:
        base_dir: Base directory containing generated_openapi and openapi spec.
                  Defaults to current working directory.
        enable_resources: Generate MCP resource templates from GET endpoints

    Returns:
        tuple: (api_metadata, security_config, modules, total_tool_count)
    """
    if base_dir is None:
        base_dir = Path.cwd()

    # Get metadata and configuration
    api_metadata = get_api_metadata(base_dir)
    security_config = get_security_config(base_dir)

    # Generate server modules with optional resources
    modules, total_tools = generate_modular_servers(base_dir, enable_resources=enable_resources)

    return api_metadata, security_config, modules, total_tools
